core/src/wallet/bitcoin/transaction_builders/BitcoinLikeTransactionBuilder.cpp
core/src/wallet/common/AbstractWallet.cpp
core/src/wallet/common/AbstractWallet.hpp

Fix a leak of sql session in AbstractAccount#getAccount. We used to pass a reference of a session in an asynchronous method and I this point the session is destroyed by RAII. The fact that it's not crashing all the time was a side effect.

Fix session reference leak

---

core/test/lib/libledger-test/TempDir.hpp

This is due to the fact that Apple doesn’t provide the experimental
headers for clang…

Fix the TempDir __MINGW__ vs. __clang__ compilation.

---

core/src/utils/Option.hpp

Some bit of background on this. It looks like (the class is Foo):
Foo(Foo&&) noexcept = default;
Is not portable as it won’t compile on clang as of today. The single
solution I found was to explicitly implement that constructor
(Option<T>). I’m not sure whether it’s linked to the fact the class is
templated or what.

Fix the move constructor of Option.

---

core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
core/src/wallet/common/AbstractAccount.cpp

This causes issues when using current block height stored in memory ... so parsing/serialization of transaction was using the wrong BIP/fork of a currency leading in some issues from Live side

Retrieve block height of currency from DB in transaction construction

---

.circleci/init_submodules.sh
core/src/wallet/BlockchainDatabase.hpp
core/src/wallet/bitcoin/Bitcoin.hpp
core/src/wallet/bitcoin/PersistentUTXOSource.cpp
core/src/wallet/bitcoin/PersistentUTXOSource.hpp
core/src/wallet/bitcoin/UTXO.cpp
core/src/wallet/bitcoin/UTXO.hpp
core/src/wallet/bitcoin/UTXOSource.hpp
core/src/wallet/bitcoin/UTXOSourceInMemory.cpp
core/src/wallet/bitcoin/UTXOSourceInMemory.hpp
core/src/wallet/common/InMemoryBlockchainDatabase.hpp
core/src/wallet/common/OperationServiceOnDB.hpp
core/src/wallet/common/PersistentBlockchainDatabase.hpp
core/test/wallet/AccountSynchronizer_test.cpp
core/test/wallet/BlocksSynchronizer_test.cpp
core/test/wallet/CMakeLists.txt
core/test/wallet/CommonFixtureFunctions.cpp
core/test/wallet/Helpers.cpp
core/test/wallet/Helpers.hpp
core/test/wallet/Mocks.hpp
core/test/wallet/OperationServiceOnDB_test.cpp
core/test/wallet/UTXOServiceSourceBased_test.cpp
core/test/wallet/UTXOSourceInMemory_test.cpp

This PR adds the persistence layer implementation for UTXO sources. This is currently based on the blockchain abstraction made by @teams2ua.
We need to provide a proper design schema / RFC / document to explicitly state what’s going on with that database blockchain as I fear it would become bloated quickly — this is not trivial and we might face issue with concurrency if we’re not crystal clear about what’s happening.
Specifically:
- The DB abstraction works on the concept of a _block_, which is NOT a blockchain’s block like from the bitcoin network. It’s a bucket that has the concept of _block height_ and is used to tag along real blocks with raw and untyped data. Another abstraction provides a typed API so that we can have typed data in those _blocks_.
- The current implementation of …

Add persistent UTXO sources.

---

core/src/ethereum/EthereumLikeExtendedPublicKey.cpp
core/src/wallet/bitcoin/database/BitcoinLikeTransactionDatabaseHelper.cpp
core/src/wallet/ethereum/EthereumLikeWallet.cpp
core/src/wallet/ethereum/ethereumNetworks.cpp
core/src/wallet/ethereum/keychains/EthereumLikeKeychain.cpp
core/test/integration/account_info_test.cpp
core/test/integration/keychains/ethereum_keychain_test.cpp
core/test/integration/keychains/keychain_test_helper.cpp

- ETH address derivation is now like Bitcoin (with respect to BIP32 and BIP44),
- We support also configurable new derivation schemes (as shown in tests), this will allow Live to support legacy derivation paths and custom (weird) ones,
- When asked about new account's creation info, client will receive a structure`{index, owners, derivations}` e.g. if we ask for first ETH account of a wallet with derivation scheme `44'/<coin_type>'/<account>'/<node>/<address>` we will receive: 
`{0, { main }, {" 44'/60'/0' "}}`
- Tests that were added were checked against returned values by a NanoS

Adapt (again) derivation address for ETH

---

tools/generate_interfaces.sh

This is not strictly required, but it will prevent you from going crazy
trying to get why you have old files that are not part of the interfaces
anymore.

Remove the ledger-core/api directory prior to generate interfaces. [skip ci]

---

core/lib/cmake/ProjectSQLiteCipher.cmake

- Define OPENSSL_LIB as crypto TARGET_FILE_DIR (instead of TARGET_FILE)
- @phaazon this is probably the reason building libcore with SQLCipher was failing ( Pierre had same issue and I fixed by that), I think reason why it was not failing on my side and CI side is because probably it was linking against system's OpenSSL which happen to have right version with all symbols defined !

SQL Cipher fix

---

core/src/debug/RotatingEncryptableSink.cpp
core/src/debug/RotatingEncryptableSink.hpp
core/src/debug/logger.cpp
core/src/debug/logger.hpp
core/src/wallet/pool/WalletPool.cpp
core/test/debug/logger_test.cpp
core/test/integration/ledger_api_blockchain_explorer_tests.cpp

We might need to reintroduce later if we ever need to encrypt logs, but
in the meanwhile, let’s get rid of that code.
LLC-154

Remove all references to passwords in the logger code.

---

.circleci/build_lib.sh
core/lib/cmake/ProjectSecp256k1.cmake

This will allow to build lib-core from one source directory with different compilers without cleaning src

Secp files in build not in src

---

CMakeLists.txt

Here, we set (erase) an important environment variable. I guess the
toolchain of polly does that (or maybe CMake, who knows). Fixes all the
problem with jni_md.h paths.

Fix JNI compilation for Apple (macOSX) platforms.

---

core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp

That happened when we went past the end of the list of operations and
the endDate was still not reached.

Fix a segfault on ERC20LikeAccount::getBalanceHistoryFor.

---

core/idl/wallet/wallet_pool.djinni
core/src/api/WalletPool.hpp
core/src/bitcoin/bech32/Bech32Parameters.h
core/src/collections/DynamicObject.cpp
core/src/collections/DynamicObject.hpp
core/src/jni/jni/WalletPool.cpp
core/src/wallet/pool/WalletPool.cpp
core/src/wallet/pool/WalletPool.hpp
core/src/wallet/pool/api/WalletPoolApi.cpp
core/src/wallet/pool/api/WalletPoolApi.hpp
core/test/collections/dynamics_tests.cpp
core/test/integration/wallet_tests.cpp

Wallet's configuration is provided to Wallet Pool when instantiating this same wallet, then persisted in our DB.
So when recovering a wallet we use same persisted configuration, so basically there is no way to update the configuration, except deleting the wallet and recreating it (SFYL)
We provide now a way to update the wallet's configuration, only fields present in the new configuration will be updated, others remain intact !
**Note**: user should be careful how to use this method:
- A new instance of wallet should be fetched from the Wallet Pool (e.g. through `getWallet` method) to get a wallet instance with the updated configuration,
- User should NOT update some fields (e.g. derivation scheme, keychain engine ...) that are defining the wallet itself (we can imagine in the future …

LLC-183: Implement updateWalletConfig on WalletPool

---

CMakeLists.txt
core/lib/cmake/ProjectSecp256k1.cmake

After some investigation, it seems to be specific to `10.10.x`:
https://forums.developer.apple.com/thread/68470
https://stackoverflow.com/questions/41865537/how-does-apples-codesign-utility-decide-which-sha-algorithms-to-sign-a-shared
This is detected just now because Live jumped from `1.1.9` to `2.6.0` in the meantime we updated so many things about our build and CI, so ...
**Notes:**
- This is a "blind" fix, no available 10.10.x macOS machine,
- ssue is specific to 10.10.x, 10.9.5 and > 10.10.x are fine

LLC-186: Add flag to avoid crash for 10.10.x macOS versions

---

core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
core/src/wallet/bitcoin/BitcoinLikeAccount.hpp

Avoid throwing when a tx is successfully broadcasted to a blockchain, if optimistic update fails, this is not a real issue because next synchro will trigger the update of local DB

LLC-181: Wrap optimistic update after tx broadcast in a Try 

---

core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
core/src/wallet/pool/WalletPool.cpp
core/src/wallet/pool/database/PoolDatabaseHelper.cpp
core/test/integration/CMakeLists.txt

Basically updateWalletConfig was not working and test covering it was not triggered because it was missing from `CMakeLists.txt` ... meh !
Also we were not using the configuration in the `UPDATE` sql call ... meh !

Fix updateWalletConfig method

---

core/src/net/HttpClient.cpp
core/src/net/HttpClient.hpp
core/src/wallet/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.cpp

This is an urgent fix for Vault ! 
Later, we can use a template based `json` method (based on `rapidjson::ParseFlag`)

ETH Fix: Parse balance from explorer as string

---

.gitmodules

We have CMakeLists.txt in our repo, this is the only difference that we care about (in upstream there where one commit to support old versions of VSs), we could move our CMakeLists.txt out of repo and be upstream, but [FAR]

Point leveldb submodule back to LedgerHQ

---

core/src/bitcoin/BitcoinLikeAddress.cpp
core/src/bitcoin/bech32/Bech32Factory.cpp
core/src/bitcoin/bech32/Bech32Factory.h
core/test/integration/transactions/bitcoin_P2WPKH_transaction_tests.cpp
core/test/integration/transactions/bitcoin_P2WSH_transaction_tests.cpp

Return optional from `newBech32Instance`: `BitcoinLikeAddress::parse` method now checks if optional has a value
Other calls to `newBech32Instance`, from`toBech32`, `fromBech32` ... should has a value (throw otherwise)

Fix Bech32

---

core/src/bitcoin/BitcoinLikeAddress.cpp
core/test/integration/transactions/bitcoin_P2WPKH_transaction_tests.cpp

Fixes:
- Missing derivation path, 
- toString method was returning a regular address instead of `bech32` one

Fix Native Segwit

---

CHANGELOG.md
core/idl/wallet/wallet_pool.djinni
core/src/api/WalletPool.hpp
core/src/jni/jni/WalletPool.cpp
core/src/wallet/pool/WalletPool.cpp
core/src/wallet/pool/WalletPool.hpp
core/src/wallet/pool/api/WalletPoolApi.cpp
core/src/wallet/pool/api/WalletPoolApi.hpp
core/src/wallet/pool/api/WalletPoolBuilder.hpp
core/test/database/BaseFixture.cpp
core/test/database/pool_tests.cpp
core/test/integration/BaseFixture.cpp

This commit removes and replaces the optional string encoding by a
mandatory string. It means that both Optional::NONE and Optional("") are
mapped to "": empty passwords are never accepted for encoding, so they
no mean “no password”.
As soon as this commit gets merged, the bindings must be updated
accordingly as well as any dependent application as this is a breaking
change.

Review password encoding.

---

core/src/math/Base58.cpp
core/src/math/Base58.hpp
core/src/utils/DerivationPath.cpp
core/src/utils/DerivationPath.hpp

Remove a lot of warnings and prepare for C++17 (throw(Something) is removed from C++)

Remove throw(Exception) from function definition

---

core/idl/wallet/ripple/ripple_like_wallet.djinni
core/src/api/RippleLikeTransaction.hpp
core/src/api/RippleLikeTransactionBuilder.hpp
core/src/jni/jni/RippleLikeTransaction.cpp
core/src/jni/jni/RippleLikeTransactionBuilder.cpp
core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
core/src/wallet/ripple/RippleLikeAccount.cpp
core/src/wallet/ripple/api_impl/RippleLikeTransactionApi.cpp
core/src/wallet/ripple/api_impl/RippleLikeTransactionApi.h
core/src/wallet/ripple/transaction_builders/RippleLikeTransactionBuilder.cpp
core/src/wallet/ripple/transaction_builders/RippleLikeTransactionBuilder.h
core/test/common/balance_history.cpp
core/test/integration/CMakeLists.txt
core/test/integration/transactions/ripple_transaction_tests.cpp

This is a required feature for Live ! 
For more infos about destination tag: 
https://developers.ripple.com/rippleapi-reference.html#payment
https://support.kraken.com/hc/en-us/articles/360000184443-What-is-the-Destination-Tag-for-XRP-Deposits-
Corresponding task: https://ledgerhq.atlassian.net/browse/LLC-222
Note: we don't retrieve/parse the destination tag from received transactions in purpose, because it is useless/not used.

Add support for destination tags for XRP

---

core/src/database/DatabaseSessionPool.hpp
core/src/database/migrations.cpp
core/src/ethereum/EthereumLikeAddress.cpp
core/src/utils/DerivationScheme.cpp
core/src/utils/DerivationScheme.hpp
core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp
core/src/wallet/ethereum/ERC20/ERC20LikeOperation.h
core/src/wallet/ethereum/EthereumLikeWallet.cpp
core/src/wallet/ethereum/factories/EthereumLikeKeychainFactory.cpp
core/src/wallet/ethereum/keychains/EthereumLikeKeychain.cpp
core/test/integration/CMakeLists.txt
core/test/integration/keychains/ethereum_keychain_test.cpp

- The next creation infos that wallets were returning were not adapted to exotic derivation schemes supported by Live,
- Add tests for weird derivation schemes

Adapt account creation infos to exotic paths 

---

core/lib/soci_sqlite3/session.cpp
core/src/database/SQLite3Backend.cpp
core/src/database/SQLite3Backend.hpp
core/test/integration/CMakeLists.txt
core/test/integration/account_creation_tests.cpp

It seems that opening an existing DB with `sqlite_key_v2` does not rewrite it with encryption ... 
So we are forced to go through `sqlcipher_export` ...
Now test `AccountCreationTest.ChangePassword` is producing an enrypted database !
Related issue: https://ledgerhq.atlassian.net/browse/LLC-232

Fix encryption of plain database

---

.circleci/build.sbt
.circleci/publish_jar.sh

I don't know why version was not changed inside of the `sbt` file, now we load directly the env variable so it should be fine !

Fix versioning of published JAR

---

.circleci/build_lib.sh
.circleci/config.yml
.circleci/copy_artifacts.sh

#223 brought Android x86_64 binaries, but didn't keep 32bit ones.
But from [Google Play announcement](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html):
> apps using native code must provide a 64-bit version (in addition to the 32-bit version)
Also Android expects 32bit x86 libs to be in the `x86` folder (and x86_64 libs to be in a `x86_64` folder).
This should fix both issues, but I wasn't able to test.

Build Android x86 32bit binaries in addition to x86_64

---

Dockerfile

While the project `README` is boasting [compatibility with Debian stretch](https://github.com/LedgerHQ/lib-ledger-core#libcore), when built with the provided `Dockerfile` the lib gets linked against the very recent glibc 2.28, making it incompatible with Linux distros older than a few month.
Don't use `testing` channel Debian for building, but actually use `stretch` as advertised.
libcore needs a newer `cmake` version than available on stretch repos, so this fetches and builds a compatible version.
The latest (3.14) version of `cmake` complains about some lines in soci's `CMakeLists.txt`. I'd rather not deal with that, and fallbacked to a previous version.
```
$ ldd -v libledger-core.so
<snip>
libc.so.6 (GLIBC_2.28) => /lib/x86_64-linux-gnu/libc.so.6 😨
<snip>
```
```
$ ldd -v …
```

Fix build env for older Linux distros

---

core/src/wallet/bitcoin/api_impl/BitcoinLikeTransactionApi.cpp
core/src/wallet/bitcoin/api_impl/BitcoinLikeTransactionApi.h

The `estimateSize` function is not implemented correctly which causes SegWit transaction fees to be too high. See: https://github.com/LedgerHQ/ledger-live-desktop/issues/1714 and https://github.com/LedgerHQ/ledger-live-desktop/issues/2001
This pull request fixes the wrong calculation. I do recommend to re-evaluate the min/max estimation parameters, because the max estimate is a bit below the https://blockstream.info virtual size calculation of a real transaction.
It is also not clear if the `marker` and `flag` should be moved from the `noWitness` to `minWitness` and `maxWitness`. https://bitcoincore.org/en/segwit_wallet_dev/#transaction-fee-estimation suggests it should be moved and Electrum also adds it to the witness data. I have left it as it was for now.

Bitcoin SegWit fee fix

---

core/src/bitcoin/BitcoinLikeAddress.cpp
core/src/bitcoin/BitcoinLikeAddress.hpp
core/src/wallet/bitcoin/keychains/BitcoinLikeKeychain.hpp
core/src/wallet/bitcoin/keychains/CommonBitcoinLikeKeychains.cpp
core/src/wallet/bitcoin/keychains/CommonBitcoinLikeKeychains.hpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeUtxoPicker.cpp
core/test/integration/synchronization/synchronization_tests.cpp

Call `toString` method instead of `toBase58` to cover native segwit transaction build.
This is related to : https://ledgerhq.atlassian.net/browse/LLC-276

Fix Bech32: fix transaction build

---

core/src/wallet/ethereum/EthereumLikeWallet.cpp
core/src/wallet/ethereum/EthereumLikeWallet.h
core/src/wallet/ethereum/keychains/EthereumLikeKeychain.cpp
core/test/integration/BaseFixture.cpp
core/test/integration/BaseFixture.h
core/test/integration/synchronization/ethereum_synchronization.cpp

We always use coinType from currency, now if the derivation scheme is setting the coinType it will be used, if not currency's coinType is used as fallback.
Note: this is needed for Live because they scan ETC accounts with `coinType = 60` which is the one of ETH !
Related to : https://ledgerhq.atlassian.net/browse/LLC-278

Retrieve cointype from derivation scheme

---

core/idl/wallet/common/wallet.djinni
core/src/api/Account.hpp
core/src/jni/jni/Account.cpp
core/src/wallet/common/AbstractAccount.cpp
core/src/wallet/common/AbstractAccount.hpp

The IDL interface is also altered to allow bindings to use it.

Provide the asRippleLikeAccount method on AbstractWallet.

---

core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.cpp

On submitting a transaction blob, the structure of the JSON response returned by the rippled server didn't match the one expected by libcore. As a result, libcore was throwing an exception even though the transaction was successfully submitted to the blockchain.
Here's a sample JSON response returned by rippled.
```json
{
"result": {
"ledger": {
"accepted": true,
"account_hash": "418DFC3919D65875A381E51A8368331D58271A67260E7AE6ADA676329BE4D0C8",
"close_flags": 0,
"close_time": 621357471,
"close_time_human": "2019-Sep-09 15:17:51.000000000",
"close_time_resolution": 10,
"closed": true,
"hash": "A2AD0F3D10B295E074E05EE1E01259DE89D7BFB06F7C4AA29B5DD763A9F7A863",
"ledger_hash": "A2AD0F3D10B295E074E05EE1E01259DE89D7BFB06F7C4AA29B5DD763A9F7A863",
"ledger_index": "49920261",
"parent_close_time": …
```

Fix parsing of successful response from rippled after submitting txn

---

core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.cpp

On broadcasting a transaction, the Ripple node may respond with a transaction hash, even though the `engine_result` key has an error code. See the list of all engine result codes here: https://xrpl.org/transaction-results.html
We could also simply checked if `engine_result` startswith `tes`, but [according to the docs](https://xrpl.org/tes-success.html):
> The code tesSUCCESS is the only code that indicates a transaction succeeded.
Hence, this should be sufficient for now.
**Bonus:** Also fixed a typo that I discovered in the same file. Not sure if the function was used by anyone.

Throw exception if Ripple node does not return tesSUCCESS

---

core/src/crypto/SECP256k1Point.cpp

We were not testing the return of secp256k1_ec_pubkey_parse correctly.
Relates to LLC-347.

Fix secp256k1 point construction.

---

core/src/database/DatabaseSessionPool.hpp
core/src/database/migrations.cpp
core/src/database/migrations.hpp
core/src/wallet/ripple/api_impl/RippleLikeTransactionApi.cpp
core/src/wallet/ripple/database/RippleLikeTransactionDatabaseHelper.cpp
core/src/wallet/ripple/explorers/RippleLikeBlockchainExplorer.h
core/src/wallet/ripple/explorers/api/RippleLikeTransactionParser.cpp
core/test/integration/synchronization/ripple_synchronization.cpp

That should fix the `nullptr` exception @meriadec saw.
Relates to LLC-349.

Add support for XRP sequence when converting an Operation into a RippleLikeTransactionApi.

---

core/src/wallet/common/AbstractWallet.cpp
core/src/wallet/tezos/database/TezosLikeAccountDatabaseHelper.cpp
core/test/integration/synchronization/tezos_synchronization.cpp

`std::bad_cast` due to a `soci` misusage of `row.get<_>` (`bool` is not accepted).

Fix double synchronization failure on Tezos

---

core/src/wallet/ripple/api_impl/RippleLikeTransactionApi.cpp

This is related to an issue faced by Vault during XRP integration.

Fix XRP: set Ledger Sequence for RippleLikeTransactionApi

---

core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.cpp

We were not parsing `DestinationTag` from Ripple transactions during account sync, and so this information was not stored in the core DB. As a result, the destination tag in the wallet daemon was always `0`.

Implement parsing of DestinationTag during Ripple account synchronization

---

core/idl/wallet/tezos/tezos_like_wallet.djinni
core/src/api/TezosConfiguration.cpp
core/src/api/TezosConfiguration.hpp
core/src/api/TezosConfigurationDefaults.cpp
core/src/api/TezosConfigurationDefaults.hpp
core/src/net/HttpClient.cpp
core/src/net/HttpClient.hpp
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/api_impl/TezosLikeOperation.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.h
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/transaction_builders/TezosLikeTransactionBuilder.cpp
core/src/wallet/tezos/transaction_builders/TezosLikeTransactionBuilder.h

This PR is meant to support Babylon update, thanks to the configuration we can switch between former protocol and the one with Babylon update. 
It is meant also to be easy to review so we can later on get rid of support of old protocol.
Removed HODL tag because I tested with `ledger-live` CLI and it's working 🚀 :
[opGvkEh34g7i3fEbErgdfePgy3F3grZHwZJoT9zuwf6xfHKEkfv](https://tzstats.com/operation/opGvkEh34g7i3fEbErgdfePgy3F3grZHwZJoT9zuwf6xfHKEkfv)

Tezos: patch code to support Babylon update

---

core/src/wallet/tezos/keychains/TezosLikeKeychain.cpp
core/test/integration/synchronization/tezos_synchronization.cpp

The restore key should be the public key since it is the one needed to create account.

Tezos: return public key instead of address from getRestoreKey method

---

core/src/wallet/common/api_impl/OperationApi.cpp
core/src/wallet/common/api_impl/OperationApi.h
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.h
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.h
core/test/integration/transactions/tezos_transaction_tests.cpp

This a patch to allow actions from originated account.
We rely on RPC call not to make serialization more complex than it is and also because those accounts are considered as legacy.
This PR was tested with Live and it's working : https://tzstats.com/KT1PTC8w6Mk6MSnx56TzMRx4Z8weLLq3oGgP

Tezos: fix operations on originated accounts

---

core/src/wallet/common/Operation.cpp
core/src/wallet/common/Operation.h
core/src/wallet/tezos/TezosLikeAccount.cpp
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/explorers/api/TezosLikeTransactionParser.cpp
core/test/integration/transactions/tezos_transaction_tests.cpp

- Originated accounts: balance and transaction history were messed up after Babylon update, now it is possible to have an operation with same `hash`, `OperationType` and `OperationTag` between Implicit and Originated accounts,
- Send max: was never taken into account

Fixes on Tezos integration

---

core/idl/wallet/tezos/tezos_like_wallet.djinni
core/src/api/TezosConfigurationDefaults.cpp
core/src/api/TezosConfigurationDefaults.hpp
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.h
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.cpp

- We assume that accounts are synced before doing a send transaction,
- We consider an address not revealed if does not have any send transaction,
- When constructing a reveal operation we reuse same parameters as the ones used for Transaction, 
- We should have a better way to detect whether the pubKey is `ED25519` or `SECP256K1`,
- I bumped also fees because after Babylon update it seems that Gas Price went up (please refer to : http://tezos.gitlab.io/protocols/005_babylon.html#gas-cost-changes)
I tested with Live 🚀 : https://tzstats.com/oomRrbFEDLiGKt1EkStyqJsMcyFj67VoHsjDNBe9Ha3WfGdGb4R

Tezos: prepend a reveal operation when needed i.e. when account is not revealed yet

---

core/src/database/query/QueryBuilder.cpp
core/test/integration/synchronization/ethereum_synchronization.cpp

When having outer joins on tables having name conflicts on column names, then adding order is throwing an error about ambiguity.

Fix OperationQuery

---

core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/api/TezosLikeTransactionParser.cpp

- Fix fees when performing a send max and a reveal at same time,
- Add burned XTZs to fees when sending to unrevealed account (storage limit is considered as mXTZ to burn),
- Fix parser for Tzstats to catch delegators addresses.

Fix tezos: fees calculation in some edge cases

---

core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp

Do not take into account XTZ that will be burned in fees, but still do in balance check when sending !
Note: this was tested and validated by @gre

Tezos Fee Fix

---

core/src/net/HttpClient.cpp
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.h

- Check `manager_key` instead of relying on number of outgoing ops from an address to check revelation, because it seems that an account could be revealed, send transactions but still unrevealed (... black magic),
- Introduce concept of `unallocated` accounts to know if we should burn XTZs or not when sending tokens,
- Avoid check of revelation on `KT` accounts, since no revelation is required for KT accounts since Babylon update.

Tezos Fix: revelation of sending account

---

ledger-core/inc/core/crypto/DeterministicPublicKey.hpp

This PR just adds the missing definition of `getPublicKeyBlake2b`.

(Re)add Blake 

---

core/src/wallet/ethereum/EthereumLikeAccount.cpp

This fix basicaly removes fees when converting internal transactions ->
operations. Taking them into account will make duplicates, as they are
already paid by the ETH transactions that generated them, or by the
contract (case of NONE type), and in this case, we don’t care about
fees.

Fix ETH negative balances.

---

core/idl/tezos/addresses.djinni
core/idl/wallet/tezos/tezos_like_wallet.djinni
core/src/api/TezosConfigurationDefaults.cpp
core/src/api/TezosConfigurationDefaults.hpp
core/src/api/TezosCurve.cpp
core/src/api/TezosCurve.hpp
core/src/tezos/TezosLikeAddress.cpp
core/src/tezos/TezosLikeAddress.h
core/src/tezos/TezosLikeExtendedPublicKey.cpp
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.h
core/src/wallet/tezos/keychains/TezosLikeKeychain.cpp
core/src/wallet/tezos/transaction_builders/TezosLikeTransactionBuilder.cpp
core/test/integration/synchronization/tezos_synchronization.cpp
core/test/integration/transactions/tezos_transaction_tests.cpp
core/test/tezos/address_test.cpp

After Babylon update, actions from `KT` accounts are actions from `tz` to a smart contract, the thing is that if a `tz` account goes to `0` balance, it gets deallocated, so it needs revelation again (SFYL), so now when we have a `tz` account (that has been emptied at some point) and then we try to make ops from its `KT` account we got stuck because the parent need revelation and from our side we considered that `KT` accounts don't need revelation (after Babylon update).
To sum up, now when we do an op from `KT` account we check revelation status of the manager account.

Fix ops from KT account with an unrevealed manager account

---

core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp

- Fix send from KT when tz parent account in unrevealed: The issue was that we should have prepend the revelation instead of appending it to the send operation.
This was tested with latest CLI of Live: https://tzstats.com/oora48f1jbqPsR6AMe7vM8SopgR9gWwby4aeBQoDGt6zLfY5MFB 🚀 
- Fix check of unallocated accounts: we use to rely on `/chains/main/blocks/head/context/contracts/<contract_id>` which is the right way to do it, but since XTZ nodes are buggy on that same endpoint, I implement a workaround, which is checking if a the account has a tx history,
- Set storage to `0` for reveal operations

Fix remaning issues with Tezos 

---

core/idl/wallet/tezos/tezos_like_wallet.djinni
core/src/api/TezosConfigurationDefaults.cpp
core/src/api/TezosConfigurationDefaults.hpp
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp

So this PR is fixing tweaking fees:
- `KT` accounts and send max: remove fees from max spendable amount when sending from KT, since fees are paid by the parent `tz` account (interaction with smart contract),
- After some feedbacks from Live:
1. it seems that `2500` was low as default fees, so I bumped it to `5000` (from what I observed from some other XTZ wallets),
2. The nodes are really fluctuating between fees of values that are crazy high, so to avoid that we fix a threshold of `6*default_fees` i.e. `30000` (again from other XTZ wallets).

Tezos fees fixes

---

ledger-core/CMakeLists.txt
ledger-core/ledger-core-config.cmake
ledger-core/lib/openssl/CMakeLists.txt

This PR allows `ledger-core` to be found via a `find_package` call. I will enhance it in another PR to take other things into account, such as:
- The build type (debug / releas).
- The target platform (x86, x64, JNI, etc.).
- Tests.
@alekece upon merging this, you can try rebasing and simply remove all `add_subdirectory`, `include_directories` or whatever and simply do this:
```cmake
find_package(ledger-core 0.1.0 REQUIRED)
target_link_directories(your-target ledger-core) # dynamic
target_link_directories(your-target ledger-core-static) # static
```

Fix packaging system of ledger-core. 

---

core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp

So I was supporting pagination thanks to the session mechanism but I forgot to tweak the `TransactionsBulk`'s `hasNext` value to force discovery.
I tested with this account `tz1ZCaJwLm6AYMUa8b8MXRvvmtgCCW44d8Qd` which has more than `100` of operation and it was working.

Tezos: fix tx pagination

---

tools/templates/CMakeLists-project-src.txt.tpl
tools/templates/CMakeLists-project.txt.tpl

The main goal of this easy-win PR is to modify our current cmake templates used by `lc` tool to use the `lib-core` target in coin project.

Modify cmake templates

---

core/src/wallet/tezos/database/TezosLikeTransactionDatabaseHelper.cpp

We were updating status of all txs with same hash, knowing that we could have different status for different transactions with same hash (e.g. succeeding revelation + failing transfer ).
This is related to : https://ledgerhq.atlassian.net/browse/LLC-431

Tezos: fix update of tezos_transactions status

---

core/idl/wallet/common/wallet.djinni
core/src/api/TimePeriod.cpp
core/src/api/TimePeriod.hpp
core/src/utils/DateUtils.cpp
core/test/common/balance_history.cpp

This brings _hour granularity_ to balance histories; feature asked by Live (LLC-474).

Add HOUR granularity for balance histories.

---

ledger-core/src/core/utils/DerivationScheme.cpp

This is needed by the Ripple project to pass test. It will also benefit other coins.

Fix DerivationScheme by backporting code from the legacy codebase.

---

ledger-core/inc/core/wallet/WalletStore.hpp
ledger-core/src/core/wallet/AbstractAccount.cpp
ledger-core/src/core/wallet/WalletStore.cpp

This PR:
- Brings in `WalletStore::eraseDataSince`, needed in tests to clean up wallets.
- Fixes the link between an `Account` and its associated `Wallet`.

Add WalletStore::eraseDataSince & fix account’s wallet link

---

core/src/wallet/tezos/TezosLikeAccount.cpp

This is related to : https://ledgerhq.atlassian.net/browse/LLC-437

Tezos: avoid creation of originated accounts based on failing origination ops

---

core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.h

Basically we were not passing the session from a call to next recursion.
This is related to : https://ledgerhq.atlassian.net/browse/LLC-472

Tezos: fix recursive sync on originated accounts

---

core/src/wallet/bitcoin/explorers/api/InputParser.cpp
core/src/wallet/bitcoin/explorers/api/OutputParser.cpp
core/src/wallet/bitcoin/explorers/api/TransactionsParser.hpp
core/test/integration/synchronization/synchronization_tests.cpp

2 changes compared to BEv2:
1. value of outputs in a string,
2. transactions returned by `/transactions` endpoint is returning 1 object instead of 1 array of 1 object.

Support BTC BEv3

---

ledger-core/idl/configuration.djinni
ledger-core/idl/derivation.djinni
ledger-core/inc/core/key/ExtendedPublicKey.hpp
ledger-core/inc/core/utils/DerivationPath.hpp
ledger-core/src/core/utils/DerivationPath.cpp
ledger-core/src/core/utils/DerivationScheme.cpp

In our legacy codebase we can found several definition and implementation of `DerivationPath`.
The purpose of this PR is to uniform that class and to expose a proper interface.  
We use signed integer type to represent index because of djinni limitation.

Inherit DerivationPath from its API interface

---

.circleci/build_lib.sh

We activate PG support only for JNI builds (for the Vault) not to introduce any issues on Live's side.
Activating it for Live would require building PG in libcore and link against it: https://ledgerhq.atlassian.net/browse/LLC-517

PostgreSQL support: build libcore with PG support only for JNI builds

---

ledger-core/idl/derivation.djinni
ledger-core/inc/core/key/ExtendedPublicKey.hpp
ledger-core/inc/core/utils/DerivationPath.hpp
ledger-core/src/core/utils/DerivationPath.cpp
ledger-core/src/core/utils/DerivationScheme.cpp

Since we modified `DerivationPath` to inherit from its api, we use `int32_t` (because of djinni limitation) instead of `uint32_t`. 
The problem is hardened derivation value is between 2^31 and 2^32 so the value cannot fit into its type anymore.
I found a "solution" : USE `int64_t` !
One more thing I refactorized a bit the `DerivationPath::parse` method

Fix integer overflow on DerivationPath

---

tools/lc

Using sh instead of bash produces
`./tools/lc: 17: ./tools/lc: Syntax error: redirection unexpected`
I suppose the syntax used l.17 is a bash-ism
The added `/usr/bin/env` is for possible non-standard OS users (nixOS notably only has /usr/bin/env to rely on)

Explicitely ask for bash in tools/lc

---

core/test/integration/synchronization/ethereum_synchronization.cpp

The problem was due to the fact most of the time, we use newDefaultPool,
which wraps the backend construction. In the case of ReorgLastBlock, the
WalletPool is hand-crafted and backend is not initialized (it’s a null
shared pointer).
Fixes LLC-514.

Fix Ethereum ReorgLastBlock test segfault.

---

ledger-core-bitcoin/inc/bitcoin/BitcoinLikeCurrencies.hpp
ledger-core-bitcoin/src/bitcoin/BitcoinLikeCurrencies.cpp

As we discuss earlier some tests put in evidence that static currency variables are not initialized in the static context when used (and CPP doesn't garantee any static order initialization).
So to fix that we use now dedicated function to create and get currencies.

Fix static order initialization in BitcoinLikeCurrencies

---

ledger-core-bitcoin/src/bitcoin/factories/BitcoinLikeWalletFactory.cpp

This PR adds the (missing) database forwarding for bitcoin.

Forward migration in BitcoinLikeWalletFactory at construct time

---

ledger-core-ethereum/test/CMakeLists.txt
ledger-core-ethereum/test/WalletTests.cpp
ledger-core/test/integration/WalletFixture.hpp

This PR allow use to test wallet (new and existing one) really quickly and with less code than actual one. 
The `testWallet` method will create `Services`, `WalletStore` and coin-specific wallet factory instances and register the `currency` given as input parameter before calling the user-specified callback (this function should contains the test code about wallet).

Add WalletFixture class

---

.circleci/build_lib.sh
CMakeLists.txt
core/lib/openssl/CMakeLists.txt
core/src/CMakeLists.txt
core/src/database/PostgreSQLBackend.cpp
core/src/database/PostgreSQLBackend.h

This relates to : https://ledgerhq.atlassian.net/browse/INFRA-1572.
Before we didn't need SSL support because we were using only Crypto libraries on OpenSSL.
Eventually we were using SSL for tests because we were implementing our own Http client with SSL support.
We didn't face that issue before with any client because Http clients are provided by the host of the Core library.
We are not only building with support of SSL but in this commit we initialize of course the SSL libraries when using PG backend.

Add SSL_SUPPORT configuration to build Core library with SSL support.

---

core/src/database/migrations.hpp
core/src/wallet/common/synchronizers/AbstractBlockchainExplorerAccountSynchronizer.h
core/src/wallet/ethereum/explorers/api/EthereumLikeTransactionParser.cpp

**Fix:** now that we are using a "real" database :trollface: we could notice some issues that we were not taking care of on DB side, as an example the input data is a `VARCHAR(255)` which is not always the case : https://explorers.api.live.ledger.com/blockchain/v3/eth/transactions/0xd1811f0c7b1dcb11bc9b28a3be194ec3d1bb273318d23e5353ee65ad6754a8e0
So now we check that and if not we drop input data. This information is used only to display details about transactions, so if an end user wants these details about their tx they have links to official explorers in the app to do so.
**Resilience:**
- Sync token deletion: issues raised by Live & Vault about failing to drop this token, now we wrap that deletion in a `Try` and if we fail to drop it we display a warning.
- `UNIQUE_CONSTRAINT` failure …

Make fixes and changes to prepare the new WD release

---

ledger-core/idl/core.djinni
ledger-core/idl/services.djinni
ledger-core/idl/wallet_store.djinni
ledger-core/inc/core/Services.hpp
ledger-core/inc/core/wallet/WalletStore.hpp
ledger-core/src/core/Services.cpp
ledger-core/src/core/wallet/WalletStore.cpp

This PR provides support for `api::Services` and `api::WalletStore`, effectively making those objects callable from foreign interfaces.

Implement Services and WalletStore API interfaces

---

ledger-core-tezos/test/AccountTests.cpp
ledger-core-tezos/test/CMakeLists.txt

As the previous PR all you have to know is in the title.
BTW, we have a long-rude discussion about the final test (e.g `info.derivation[0] == "44'/1729'/0/0/0"`) and decide to comment it. The comment just above the test explains why.

Add XTZ account test

---

core/test/common/balance_history.cpp
ledger-core/inc/core/database/DatabaseSessionPool.hpp
ledger-core/inc/core/database/Migrations.hpp
ledger-core/src/core/Services.cpp
ledger-core/src/core/database/DatabaseSessionPool.cpp

We need to ensure all coins’s database migrations are rolled back before
rolling back the ledger-core one. This is due to the fact internally,
tables might have relationship and foreign keys. Some database backends
will automatically erase lines in child tables but the structure — i.e.
the tables themselves — will remain in database.
In the doubt, it’s better to drop tables in order.
Relates to LLC-509.

Add support for ordered migration rollbacks.

---

core/idl/database/database.djinni
core/lib/soci/core/session.cpp
core/lib/soci/core/session.h
core/lib/soci/core/soci-backend.h
core/lib/soci_postgresql/session.cpp
core/lib/soci_postgresql/soci-postgresql.h
core/lib/soci_sqlite3/session.cpp
core/lib/soci_sqlite3/soci-sqlite3.h
core/src/api/DatabaseConnection.hpp
core/src/database/proxy_backend/session.cpp
core/src/database/proxy_backend/soci-proxy.h
core/src/jni/jni/DatabaseConnection.cpp
core/src/jni/jni/DatabaseConnection.hpp
core/test/database/MemoryDatabaseProxy.cpp
core/test/database/MemoryDatabaseProxy.h

With the current version of soci, when a `connection_pool` is created, a
buffer is allocated with, for each element in the buffer, a pair `(bool,
session*)`. The boolean value indicates whether the session is free or
not (this is pretty bad way to encode a pool, but whatever). When a
session is freed, the boolean gets changed and then opening a new
session will reuse that slot.
However, when a session has been idleing for a while, it’s possible that
the database backend (e.g. PostgreSQL) kills the connection held in the
session for timeout. The `soci` library doesn’t see that and assumes the
session is still valid -> we hit errors, which get propagated as
`std::runtime_error` in our codebase.
This commit fixes the problem by introducing a `is_alive()` function on
the session that allows a …

Add support for failover behavior in soci connection pools.

---

ledger-core-bitcoin/inc/bitcoin/database/Migrations.hpp
ledger-core-bitcoin/src/bitcoin/database/Migrations.cpp
ledger-core-bitcoin/test/SynchronizationTests.cpp
ledger-core-ethereum/inc/ethereum/database/Migrations.hpp
ledger-core-ethereum/src/ethereum/database/Migrations.cpp
ledger-core-ripple/inc/ripple/database/Migrations.hpp
ledger-core-ripple/src/ripple/database/Migrations.cpp
ledger-core-ripple/test/CMakeLists.txt
ledger-core-tezos/inc/tezos/database/Migrations.hpp
ledger-core-tezos/src/tezos/database/Migrations.cpp
ledger-core/CMakeLists.txt
ledger-core/idl/configuration.djinni
ledger-core/idl/database.djinni
ledger-core/inc/core/database/DatabaseBackend.hpp
ledger-core/inc/core/database/DatabaseSessionPool.hpp
ledger-core/inc/core/database/Migrations.hpp
ledger-core/inc/core/database/PostgreSQLBackend.hpp
ledger-core/lib/CMakeLists.txt
ledger-core/lib/soci_postgresql/CMakeLists.txt
ledger-core/src/CMakeLists.txt
ledger-core/src/core/database/DatabaseBackend.cpp
ledger-core/src/core/database/DatabaseSessionPool.cpp
ledger-core/src/core/database/Migrations.cpp
ledger-core/src/core/database/PostgreSQLBackend.cpp
ledger-core/test/integration/BaseFixture.cpp
ledger-core/test/integration/BaseFixture.hpp

As the title above said this PR contains the backport of PostSQL support into the segregated `lib-ledger-core` and a method to know if the main `ledger-core` library was compiled with `PG_SUPPORT` (efficient way to instance the correct database backend in coin-specific library).

Backport PostgreSQL support 

---

core/idl/wallet/configuration.djinni
core/src/api/Configuration.cpp
core/src/api/Configuration.hpp
core/src/wallet/common/synchronizers/AbstractBlockchainExplorerAccountSynchronizer.h

Unset sync token when falling in reorg situation because explorers are not trustworthy on that feature
**HODL:** I will add a config to deactivate sync tokens

Sync token removal in reorganisation use case

---

core/src/wallet/bitcoin/transaction_builders/BitcoinLikeUtxoPicker.cpp
core/test/integration/CMakeLists.txt
core/test/integration/transactions/bitcoin_P2PKH_transaction_tests.cpp
core/test/integration/transactions/transaction_test_helper.h

Prevent picker from using UTXO when the amount is less than dustAmount
Small issue with local tests, so using CI for now.

Prevent BitcoinLike UTXO picker from using tx<Dust

---

ledger-core/CMakeLists.txt
ledger-core/ledger-core-config.cmake

This PR moves _targets_ around so that we don’t include them if we’re not making them in the first place.

Fix CMake exports so that we don’t export non-existing targets.

---

core/test/integration/ledger_api_blockchain_explorer_tests.cpp

`std::optional<T>` has a non-explicit constructor that authorizes to build
the optional with a `T const &`, but it cannot be transitive (i.e. the
original code tried to do `char const * -> std::string const & ->
optional`.

Fix LedgerApiEthereumLikeBlockchainExplorerTests::PostEstimatedGasLimit.

---

ledger-core-bitcoin/test/ExplorerTests.cpp
ledger-core-ethereum/test/CMakeLists.txt
ledger-core-ethereum/test/ExplorerTests.cpp
ledger-core/test/integration/ExplorerFixture.hpp

This PR includes missing explorer tests (basically linked to ethereum) and implement a `ExplorerFixture` class which is used in bitcoin and ethereum tests.
We need to merge this PR as soon as possible to unlock the backport of the PR #429.

Add missing explorer tests

---

.circleci/cmake-install.sh
.circleci/config.yml
.circleci/setup_debian.sh
CMakeLists.txt
appveyor.yml
core/src/CMakeLists.txt

Update CMake and enable https://cmake.org/cmake/help/v3.15/policy/CMP0091.html#policy:CMP0091 to compile all subprojects with static MS runtime

Use static MS runtime

---

CMakeLists.txt

This reverts commit 97d983ccb9a7f44ee8a1415785ef204292099ad7.
Keep using newer version of CMake, but revert compilation
with static MS runtime.
With Live team we decided, to include VS redistributable inside the installer,
to make another native modules, that depends on runtime works the same way as before
Electron 6

Revert "Use static MS runtime"

---

core/src/wallet/ethereum/EthereumLikeAccount.cpp

Passing reference on temporary object is unsafe and make ASAN very unhappy.

Fix rvalue passed to soci as reference.

---

ledger-core/lib/soci/core/CMakeLists.txt

This PR is quite simple : link `dl` library to `soci-core`.

Fix undefined reference to dl on ubuntu

---

cmake/CompilerWarnings.cmake
ledger-core-bitcoin/src/CMakeLists.txt
ledger-core-ethereum/src/CMakeLists.txt
ledger-core-ripple/src/CMakeLists.txt
ledger-core-tezos/src/CMakeLists.txt
ledger-core/src/CMakeLists.txt

The PR aims to enable a bunch of compiler warnings for `MSVC`, `Clang`, `AppleClang` and `Gcc`.
The compilation of `lib-ledger-core` - more precisely `ledger-core` and all the coins - triggers a lot of warnings so the compiler warnings feature is optional  and disable by default.
Compiler warnings can be enabled such as :
```
cmake -DENABLE_WARNINGS=ON -DWARNINGS_AS_ERRORS=ON ...
```

Add compiler warnings

---

cmake/ProjectSettings.cmake
ledger-core-bitcoin/CMakeLists.txt
ledger-core-ethereum/CMakeLists.txt
ledger-core-ripple/CMakeLists.txt
ledger-core-tezos/CMakeLists.txt
ledger-core/CMakeLists.txt

This PR aims to add `ccache` support and abstract some project settings.
`ccache` is used by default if the executable is found.

Add ccache support and project settings

---

.gitignore
core/src/wallet/ethereum/EthereumLikeAccount.cpp

Those were missing because of two issues:
- We didn’t create internal transactions UUID correctly. We initially
assumed that we have only one internal transaction (uuid =
transaction_uuid + hash_data, for short). This fix adds the index of
the internal transaction to generate different UUIDs and then get them
all.
- We didn’t filter correctly transactions that don’t concern us. We then
end up (at least on the core side) with several `NONE` transactions.
The filtering here basically requires to discard internal transactions
which type is set to `NONE`, since they don’t concern us — the
explorers seem to still send us those transactions as they don’t
filter them from the parent transaction.

LLC-572 — Fix missing internal transactions for Ethereum.

---

core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.h

@RomanWlm could you please complete with right ticket (could not find it).
**NOTE**: it seems that `The format of the marker field is intentionally undefined.` (from: https://xrpl.org/markers-and-pagination.html), so this is valid at least for `s3` and `s2`.

Fix XRP: marker to be set to Uint64 instead of string

---

core/src/wallet/bitcoin/transaction_builders/BitcoinLikeTransactionBuilder.cpp
core/test/integration/transactions/bitcoin_P2PKH_transaction_tests.cpp

This is related to : 
- LVS: https://ledgerhq.atlassian.net/browse/LVS-141,
- Mirrored by LLC: https://ledgerhq.atlassian.net/browse/LLC-629

Fix BCH: construct P2PKH and P2SH output scripts even in case of cash addresses

---

.circleci/deploy_fat_lib.sh

XCode had a recent change of heart regarding embedded library architectures allowed in a build so, long story short, we have to change the way we embed `ledger-core.framework` in Ledger Live mobile, meaning we don't use _thin_ frameworks anymore but only the _fat_ one, in which we need _all_ the architectures, including `x86_64`.

[iOS] Add x86_64 to fat framework

---

core/src/wallet/stellar/keychains/DefaultStellarLikeKeychain.cpp

- Use hex public as restore key for XLM because the live uses it to restore accounts.

Use public key as restore key for XLM integration

---

core/idl/wallet/configuration.djinni
core/src/api/StellarConfiguration.cpp
core/src/wallet/stellar/explorers/horizon/HorizonFeeStatsParser.cpp
core/test/coin-integration/stellar/horizon_explorer_tests.cpp

This PR changes:
- The base url used by the Explorer in order to use our proxy
- Change /fee_stat implementation to match last version of Horizon

Change explorer base URL

---

ledger-core/inc/core/math/BaseConverter.hpp
ledger-core/src/core/math/BaseConverter.cpp

`math/BaseConverter` was added in libcore v1 and not ported in libcore v2 yet.
It will be used in Algorand integration.
This PR only updates include headers to be v2-compliant, no functional modification.

Port BaseConverter from libcore v1 to v2

---

core/src/wallet/bitcoin/transaction_builders/BitcoinLikeUtxoPicker.cpp

The problem was due to immediate contexts being used, which stack
fillInputs calls and eventually lead to a segmentation fault. We
detected the problem in VSD-26, leading to LLC-648 after seeing first a
520+-deep callstack on the JVM / Wallet Daemon, and I reproduced locally
by limitting the size of the stack to 1MB on native tests (SIGSEGV after
a 8k+-deep callstack).
This commit doesn’t do anything more than fixing the stack problem. Slow
issues are to be solved in another PR and new issues.

LLC-648 + VSD-26 — Fix stack exhaustion with recursive futures in the Bitcoin UTXO picker.

---

core/src/math/BigInt.h
core/src/traits/arithmetic.hpp
core/test/math/bigint_tests.cpp

Current implementation of BigInt::assignScalar doesn't build when passing an unsigned integer because std::abs is not defined for unsigned type (and doesn't make much sense).
This PR add 2 different implementation of BigInt::assignScalar<T> for signed and unsigned type and a test to create BigInt from unsigned scalar types.

Fix BigInt assign scalar

---

ledger-core/src/core/crypto/HMAC.cpp

Port to libcore v2 the support of both OpenSSL 1.0.0 & 1.1.0 for HMAC.
This should be the same changes in `HMAC.cpp` as in https://github.com/LedgerHQ/lib-ledger-core/commit/64247e992fcc2447565628b6469ae4acb1d86fb1

Port support of both OpenSSL 1.0.0 & 1.1.0 for HMAC from libcore v1 to v2

---

core/lib/CMakeLists.txt

The PR aims to fix the undefined symbols related to `dl` library on Unix systems.

Undefined symbols related to dl library

---

ledger-core/src/core/utils/Hex.cpp

- Rename `hex.cpp` -> `Hex.cpp`. That issue wasn’t visible on macOS
because LOL FILESYSTEMS.
- Add inclusion of stdexcept. I don’t know why it hasn’t failed already.
I guess even Stroustrup doesn’t know that.

Fix compilation of Hex.cpp.

---

appveyor.yml

AppVeyor was releasing new artifacts on 3.3.0 instead of 3.4.0

Bump libcore version in appveyor

---

core/test/integration/synchronization/synchronization_tests.cpp

Current URL is broken. https://ledgerhq.atlassian.net/browse/MO-1050
There is no need for a special URL, this one was probably used during migration to V3.

Change base URL in test to production URL

---

core/src/wallet/stellar/explorers/horizon/HorizonTransactionParser.cpp
core/test/coin-integration/stellar/synchronization_tests.cpp

Horizon 1.3.0 update changed the way fees are serialized from int64 to string.
Also source_sequence_account was not fetched properly (unused value in live).
https://github.com/stellar/go/releases/tag/horizon-v1.3.0

Fix fees parsing on XLM

---

.circleci/setup_debian.sh
.circleci/setup_macos.sh
CHANGELOG.md
CMakeLists.txt
appveyor.yml
core/src/wallet/stellar/explorers/horizon/HorizonTransactionParser.cpp
core/test/coin-integration/stellar/synchronization_tests.cpp
core/test/integration/synchronization/synchronization_tests.cpp

This PR:
- Bump libcore version to 3.4.1
- Rebase develop on master
Changelog:
- Fix SBT download failures on the CI (for Debian and MacOS)
- Fix a BTC test using a deprecated URL
- Fix Stellar fee parsing for Horizon 1.3.0

Release version 3.4.1

---

core/src/cosmos/CosmosLikeAddress.cpp
core/src/wallet/cosmos/factories/CosmosLikeKeychainFactory.cpp
core/src/wallet/cosmos/keychains/CosmosLikeKeychain.cpp

This *might* fix an iOS specific error

[cosmos] Return empty derivationPath for CosmosLikeAddress

---

core/src/wallet/cosmos/CosmosLikeAccount.cpp
core/src/wallet/cosmos/CosmosLikeAccount.hpp

- The fees need to be properly computed on inflation if we have the
actual gasUsed in the transaction.
- The fees are always included as an operation.amount so the
balanceHistory from CosmosLikeAccount should never care about
operation.fees from the received operationQuery

[cosmos] Handle fees properly in balanceHistory

---

core/src/wallet/cosmos/CosmosLikeAccount.cpp
core/src/wallet/cosmos/CosmosLikeAccount.hpp
core/test/cosmos/Fixtures.cpp
core/test/cosmos/Fixtures.hpp
core/test/cosmos/db_test.cpp

The filtering is done just before converting an incoming Transaction to
an Operation suitable for database storage.
A test is added to check that a FeeMessage is filtered out when the
payer is not the current account.

[cosmos] Do not include fees user didn't pay in operations

---

core/idl/wallet/cosmos/wallet.djinni

The shift for production URL will be done once the proxy is setup. This
change is still necessary because the old node will be decommissioned
soon.

Use Production url for cosmos

---

core/idl/wallet/cosmos/wallet.djinni

`cosmos.coin.ledger.com` doesn't answer yet

Use "dev" address for Cosmos explorer

---

core/src/wallet/bitcoin/database/BitcoinLikeTransactionDatabaseHelper.cpp

The SQL queries to remove mempool operation were wrong.
Since they were based on transaction hash it actually partially removes transactions even for other accounts.
The fix uses transaction_uid to drop only transaction bound to the account and avoid side effects on other accounts.

Fix SQL query to remove operation in mempool for a given account

---

core/src/database/migrations.cpp

This PR fixes a typo in the SQL query for doing a rollback of database schema version 21

Fix rollback script for migration 21

---

.circleci/cmake-install.sh
.circleci/config.yml
.circleci/setup_debian.sh
Dockerfile

- Factorize env setup in a docker image `ledgerhq/lib-ledger-core-build-env`
- Split build_linux_release into 3 jobs:
- build_linux_release: generate artifacts for linux and linux with OpenSSL 1.1
- build_linux_jni_release: generate artifact for linux with JNI
- build_android_release: generate artifact of android (archs: x86_64, armeabi-v7a, arm64-v8a)

Faster CI builds

---

.circleci/build_lib.sh
.circleci/setup_macos.sh
core/src/database/migrations.cpp

This PR fixes the CI which built invalid binary with wrong version of OpenSSL.
It also fixes database migration for PGSQL (muxed_account_version data type from STRING to VARCHAR(255))

Fix develop branch for JNI and PGSQL

---

core/idl/preferences/preferences.djinni
core/src/api/PreferencesBackend.hpp
core/src/jni/jni/PreferencesBackend.cpp
core/src/preferences/Preferences.cpp
core/src/preferences/PreferencesBackend.cpp
core/src/preferences/PreferencesBackend.hpp

This is just for consistency as both `key` and `value` are binary (`std::vector<uint8_t>`) in `api::PreferencesChange`.

Change return type of PreferencesBackend::get from string to binary

---

core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
core/src/wallet/bitcoin/database/BitcoinLikeUTXODatabaseHelper.cpp
core/src/wallet/bitcoin/explorers/BitcoinLikeBlockchainExplorer.hpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeStrategyUtxoPicker.cpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeStrategyUtxoPicker.h
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeTransactionBuilder.cpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeTransactionBuilder.h
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeUtxo.cpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeUtxo.hpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeUtxoPicker.cpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeUtxoPicker.h
core/src/wallet/common/Amount.h
core/test/bitcoin/bitcoin_utxo_picket_tests.cpp

This PR aims to improve - in term of **time** - the performance of the empty transaction built for Bitcoin.
Several strategies has been applied : 
* Request once -  from DB - all information needed for the UTXO strategy pickers
* Remove the HTTP/SQL calls to get missing information from transactions
* Avoid copies as much as possible without refactorize all the legacy code
There are still place to another improvement such as :
* Remove in-place calculation from `BigInt` to integer in UTXO strategy pickers 
* Rewrite `Future` to accept non-const parameters and avoid deep copy; in other term avoid extra allocations
| # | Amount | Strategy | Legacy Library Response Time | Improved Library Response Time | Response Time Change  | 
| -- | ---------- | ----------- | …

Empty transaction built improvement

---

core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.h

We now depend on the explorer instead of looking at the transactions.
Doing a transaction check is tricky, because of the fact failed
transactions are still recorded on the blockchain (someone has to pay
the fees), but they don’t credit the recipient account; so it still
stays unfunded.

LLC-692 | Fix the way we check whether a Tezos account is funded.

---

core/src/CMakeLists.txt

This commit fix a segfault on Linux occuring when the system openssl is different from the libcore embedded openssl. It prevents openssl from automatically export its symbols which was causing the segfault in the first place.

Fix segfault related to openssl

---

core/src/utils/Option.hpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeUtxo.hpp

For some reason `~Option()` destructor is not found at runtime, _only on Android integration_, starting from commit 5b10c2e6c281995e379ea26d73770cf9c91e82cd.
Further investigation will be needed to check whether:
1. `~Option()` was never defined but never needed until that commit... seems unlikely...
2. `~Option()` did exist before that commit and disappeared... no idea why...

Add ~Option() destructor to fix Android runtime linkage

---

core/src/wallet/algorand/AlgorandWalletFactory.cpp
core/test/algorand/AlgorandExplorerTests.cpp
core/test/algorand/AlgorandSynchronizationTests.cpp

PR to update Algorand reverse proxy endpoints:
- Make libcore hit https://algorand.coin.ledger.com instead of https://algorand.coin.staging.aws.ledger.com
- Make libcore tests hit https://algorand.coin.staging.aws.ledger.com instead of https://testnet-algorand.api.purestake.io

Update Algorand reverse proxy endpoints for libcore and tests

---

core/src/wallet/algorand/database/AlgorandOperationDatabaseHelper.cpp

DB update of an Algorand operation causes a crash on Windows, and is not actually required because the content of an operation never changes after initial creation.

Remove DB update of Algorand operation

---

core/idl/wallet/bitcoin/bitcoin_like_wallet.djinni
core/src/api/BitcoinLikeAccount.hpp
core/src/api/BitcoinLikeTransactionBuilder.hpp
core/src/jni/jni/BitcoinLikeAccount.cpp
core/src/jni/jni/BitcoinLikeTransactionBuilder.cpp
core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
core/src/wallet/bitcoin/BitcoinLikeAccount.hpp
core/src/wallet/bitcoin/api_impl/BitcoinLikeTransactionApi.cpp
core/src/wallet/bitcoin/api_impl/BitcoinLikeTransactionApi.h

In libcore Djinni APIs, change some functions parameters from optional to not optional.
The change is safe because:
- `BitcoinLikeAccount::buildTransaction` is always called by live-common with a non-optional value: https://github.com/LedgerHQ/ledger-live-common/blob/master/src/families/bitcoin/libcore-buildTransaction.js#L56
- `BitcoinLikeTransactionBuilder::parseRawUnsignedTransaction` is never used from client side, but fix it anyway.
This PR fixes a probable regression introduced by https://github.com/LedgerHQ/djinni/commit/7bd8220133a1e6fdf6dfd953d51ccf477daeb4b5
With issue shown below:

Make some Djinni API functions params non-optional

---

core/src/wallet/algorand/AlgorandAccount.cpp
core/src/wallet/algorand/AlgorandBlockchainExplorer.cpp

Algorand Explorer causes crashes when there is no network connectivity --> sanitize JSON in case of no data received.

Protect json reads in Algorand Explorer to prevent crashes

---

core/src/wallet/algorand/AlgorandBlockchainExplorer.cpp
core/test/algorand/AlgorandAccountTests.cpp
core/test/algorand/AlgorandDatabaseTests.cpp
core/test/algorand/AlgorandExplorerTests.cpp
core/test/algorand/AlgorandSynchronizationTests.cpp

In Algorand tests, as long as the reverse proxy was not available, Purestake API key was used from an env variable.
Now that the reverse proxy is used it manages the API key itself so we don't need to use it from an env variable anymore.
This fixes all Algorand tests currently failing in CI.

Fix bad management of Algorand API key in Algorand tests

---

core/src/wallet/cosmos/CosmosLikeAccount.cpp

Apparently all advertised/signed fees are consumed in transaction and no
ratio of actual gas usage is used regarding fee computation

[cosmos] Remove gas ratio multiplier in fees

---

core/src/wallet/cosmos/explorers/CosmosLikeBlockchainExplorer.hpp
core/src/wallet/cosmos/explorers/GaiaCosmosLikeBlockchainExplorer.cpp
core/src/wallet/cosmos/explorers/GaiaCosmosLikeBlockchainExplorer.hpp
core/test/integration/synchronization/cosmos_synchronization.cpp

If we do not fetch the block data each time a transaction is
fetched (although saving HTTP calls), then :
- The blockHash of the transaction is empty, therefore no block_uid can
be computed from the tx.block
- The block_uid column of the transaction in the database therefore
stays `NULL`
- When querying the operations later, the LEFT JOIN of
cosmos_transactions with blocks will fail to find a block
- Final state : the queried operation has no "height" information
Having no "height" information is a problem because this is used by
Ledger Live to compute the count of confirmations for a given Operation.

[cosmos] Fetch block data on each transaction fetch

---

core/src/api/CosmosConfigurationDefaults.cpp
core/src/wallet/cosmos/CosmosLikeAccount.cpp
core/src/wallet/cosmos/CosmosLikeAccount.hpp

This fixes an issue where the "getSequence()" call was not up to date
when called more often than the full account synchronization.
The update is _not_ called on getAccountNumber() since this value is
immutable.

[cosmos] Force account-level data synchronization on getSequence

---

core/src/database/query/QueryBuilder.cpp
core/src/database/query/QueryBuilder.h
core/src/database/query/filters_impl.cpp
core/src/wallet/common/OperationQuery.cpp
core/test/database/query_filters_tests.cpp
core/test/integration/synchronization/synchronization_tests.cpp

Current version of the libcore considers that block_height is a field of operations table. Block height is however get from a outer join with the block tables. This PR fixes the query filter and ordering when it involves block height. It also adds some tests around it.

Fix operation queries when it involves block_height

---

core/idl/wallet/tezos/tezos_like_wallet.djinni
core/src/api/TezosLikeAccount.hpp
core/src/jni/jni/TezosLikeAccount.cpp
core/src/wallet/tezos/TezosLikeAccount.h
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.h
core/test/tezos/ED25519_transaction_test.cpp
core/test/tezos/P256_transaction_test.cpp
core/test/tezos/SECP256K1_transaction_test.cpp

This PR adds a new function to an XTZ account: `getCurrentDelegate`
It allows the caller to retrieve the address of the current delegation, empty if none.

[WIP] Nrt tezos get current delegate

---

core/idl/wallet/tezos/tezos_like_wallet.djinni
core/src/api/TezosLikeAccount.hpp
core/src/jni/jni/TezosLikeAccount.cpp
core/src/wallet/tezos/TezosLikeAccount.h
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.h
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.cpp
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.h
core/test/tezos/SECP256K1_transaction_test.cpp

This PR provides a way to get much better XTZ gas and fees estimations. It's merely a merge of the work done by @gagbo: 
#643 
Conflicts:
-	core/src/tezos/TezosLikeExtendedPublicKey.cpp
-	core/src/wallet/tezos/TezosLikeAccount2.cpp
-	core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp
-	core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp

[WIP] [COIN 584] [XTZ] Improve Fees and GasLimit using a RPC node

---

.gitmodules

corrects failure during git submodule update
```
root@capnmagneto:~/lib-ledger-core# git submodule update
Cloning into '/root/lib-ledger-core/core/test/lib/libuv'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:libuv/libuv.git' into submodule path '/root/lib-ledger-core/core/test/lib/libuv' failed
```

repair path to libuv github repository

---

core/idl/wallet/cosmos/wallet.djinni
core/src/api/CosmosConfigurationDefaults.cpp
core/src/config/Networks.cpp
core/src/database/DatabaseSessionPool.hpp
core/src/database/migrations.cpp
core/src/wallet/pool/database/CurrenciesDatabaseHelper.cpp

- Set currency identifier of the `cosmoshub+4` chain to `cosmos`
- Trigger the migration to remove cosmos account history
- Change the default endpoint

Switch cosmos mainnet to Stargate

---

core/src/wallet/cosmos/CosmosLikeAccount.cpp
core/src/wallet/cosmos/CosmosLikeAccount.hpp

Fixes an issue where calling "estimateGas" too quickly after a broadcast
would actually still use an old sequence number.

[ATOM] Wait for updateAccountFromNetwork

---

core/test/algorand/AlgorandAccountTests.cpp
core/test/algorand/AlgorandExplorerTests.cpp
core/test/algorand/AlgorandSynchronizationTests.cpp
core/test/algorand/CMakeLists.txt

**Context**: we changed our Algorand node provider from PureStake to host it ourselves with Leger infra (https://ledgerhq.atlassian.net/browse/LL-5485).
However our infra doesn't provide a TestNet anymore, so we have to disable the libcore tests that were based on the TestNet.

LL-5485 LL-5782 [Algorand] Disable tests based on TestNet

---

core/src/wallet/bitcoin/BitcoinLikeAccount.cpp

As we merge foreign outputs in BTC-like currencies, we cannot directly
access the "previous transaction" output with the index. It is necessary
to scan every output and find it with a matching predicate
Fixes VSD-678

fix(btc): correct prev output in optimistic update

---

core/src/wallet/common/AbstractAccount.cpp
core/src/wallet/common/AbstractAccount.hpp
core/src/wallet/tezos/TezosLikeAccount.cpp
core/src/wallet/tezos/TezosLikeAccount.h
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/synchronizers/TezosLikeAccountSynchronizer.cpp
core/test/integration/synchronization/cosmos_synchronization.cpp
core/test/integration/synchronization/tezos_synchronization.cpp
shell.nix

This allows to pinpoint the various errors in this test, with an easy
explorer link from the test logs.
Also add an initial `shell.nix` to ease local compilation down the road (not fully tested in pure environment yet)

Add verbosity in XTZ tests, fix medium xpub sync

---

core/src/wallet/bitcoin/BitcoinLikeAccount.cpp

#807 didn't update the fees at all, so at that point it's just a guess. The error is
```
Core Warn: 2021-09-01T12:05:29Z+00:00 W: ledger.correlation_id=1551013d-9c85-45e0-9134-3769a8c32191 Optimistic update failed for broadcasted transaction [hash: fdbb2051fdedb281d808af62b3840a28bba91ca55c7d6876219d35e4dc34e07c] with errcode RUNTIME_ERROR: Dynamic exception type: std::experimental::bad_optional_access
std::exception::what: bad optional access
```
and this is the first suspect `getValue()` I found by manually following the code

[BTC] Update fees in optimistic update before insertion

---

core/src/wallet/bitcoin/keychains/CommonBitcoinLikeKeychains.cpp
core/src/wallet/bitcoin/keychains/CommonBitcoinLikeKeychains.hpp
core/test/integration/CMakeLists.txt
core/test/integration/keychains/common_bitcoin_keychain_test.cpp
core/test/integration/keychains/keychain_test_helper.h
core/test/integration/keychains/p2sh_keychain_test.cpp

- Remove internal state from BTC keychains 
- Load the latest state from Redis at each use, instead

VG-1728: Remove the use of internal state in keychains

---

CMakeLists.txt
core/src/database/DatabaseSessionPool.hpp
core/src/database/migrations.cpp
core/src/database/migrations.hpp

* The fix consists in creating specific indexes in the sql db to accelerate `on delete cascade` for bitcoin transactions.
* bump patch version
This fix addresses the following defect: 
[VG-2280: CaaT reseed does not work on big account](https://ledgerhq.atlassian.net/browse/VG-2280)

[VG-2280] Fix very long delete operations on sql db for bitcoin transactions

---

CMakeLists.txt
core/src/events/ProgressNotifier.h
core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp
core/src/wallet/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.cpp

Optimizations in memory management in method  `LedgerApiEthereumLikeBlockchainExplorer::getERC20Balances`

[VG-2532] Fix excessive memory usage when getting erc20 balances

---

.github/workflows/nix_release_builds.yml
.gitignore
nix/scripts/build_jar.sh
nix/scripts/export_libcore_version.sh

Replaces libcore artifact version from "4.1.1-SNAPSHOT" to 
- for releases: ${LIB_VERSION} (from CMakeLists.txt)
- for pushes: ${LIB_VERSION}-${latest-reachable-tag}-${N}-${commit-hash}-SNAPSHOT"
- for pull requests: ${LIB_VERSION}-${BRANCH_NAME}-${BRANCH_LENGTH}-${commit_hash}-SNAPSHOT
where ${N} - number of commits from last reachable tag.

Fix artifacts upload

---

CMakeLists.txt
core/idl/wallet/tezos/tezos_like_wallet.djinni
core/src/api/TezosLikeAccount.hpp
core/src/api/TezosLikeTransaction.hpp
core/src/jni/jni/TezosLikeAccount.cpp
core/src/jni/jni/TezosLikeTransaction.cpp
core/src/wallet/common/Operation.cpp
core/src/wallet/common/Operation.h
core/src/wallet/tezos/TezosLikeAccount.cpp
core/src/wallet/tezos/TezosLikeAccount.h
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.h
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/api/TezosLikeTransactionParser.cpp
core/src/wallet/tezos/transaction_builders/TezosLikeTransactionBuilder.cpp

:warning: the database has be wiped before using this new version, breaking change in operation `uid` computation  !  
The aim is to provide an `operation_uid` in the crafted Tezos transactions which will necessarily match with the operation `uid` computed during the account synchronization. A great description of the problem is provided on [VG-3094](https://ledgerhq.atlassian.net/browse/VG-3094). Basically, this PR updates the formula for computing the Tezos operation `uid`. A tezos account method `computeOperationUid` has been added to compute the same operation uid from a crafted transaction. 
* change tezos operation uid formula to `accountUId + counter + TxOpIndex + TxOpType (+ additional) + OperationType`
* add methods to tezos transaction to retrieve the non-reveal operation type / …

[VG-3094] Add operation_id in tezos transactions and update of uid formula

---

CMakeLists.txt
core/src/wallet/tezos/TezosLikeAccount.cpp
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/test/common/CMakeLists.txt
core/test/common/operation.cpp
core/test/integration/account_creation_tests.cpp
core/test/tezos/CMakeLists.txt
core/test/tezos/ED25519_transaction_test.cpp
core/test/tezos/P256_transaction_test.cpp
core/test/tezos/SECP256K1_transaction_test.cpp
core/test/tezos/tezos_account.cpp

* Fix potential regression on Tezos account sync
* Addition of unit tests to cover changes from previous PRs #848 & #849 
* Bump patch version
* [VG-3094](https://ledgerhq.atlassian.net/browse/VG-3094)

Fix potential regression on Tezos account sync + Addition of unit tests 

---

CMakeLists.txt
core/src/wallet/tezos/TezosLikeAccount.cpp
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/test/common/CMakeLists.txt
core/test/common/operation.cpp
core/test/integration/account_creation_tests.cpp
core/test/tezos/CMakeLists.txt
core/test/tezos/ED25519_transaction_test.cpp
core/test/tezos/P256_transaction_test.cpp
core/test/tezos/SECP256K1_transaction_test.cpp
core/test/tezos/tezos_account.cpp

Copied from #850 (fix merge odering of PRs)
Changes:
Fix potential regression on Tezos account sync
Addition of unit tests to cover changes from previous PRs https://github.com/LedgerHQ/lib-ledger-core/pull/848 & https://github.com/LedgerHQ/lib-ledger-core/pull/849
Bump patch version
References
[VG-3094](https://ledgerhq.atlassian.net/browse/VG-3094)

Fix potential regression on Tezos account sync + Addition of unit tests

---

core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp

Fixes stack corruption in Tezos tests.

Add return to TezosLikeTransactionApi::setOperation*

---

core/idl/wallet/bitcoin/bitcoin_like_wallet.djinni
core/src/api/BitcoinLikeTransaction.hpp
core/src/api/BitcoinLikeTransactionBuilder.hpp
core/src/jni/jni/BitcoinLikeTransactionBuilder.cpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeTransactionBuilder.cpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeTransactionBuilder.h
core/test/fixtures/txes_to_wpkh._fixtures.cpp
core/test/fixtures/txes_to_wpkh_fixtures.h
core/test/integration/http_cache/BitcoinMakeTransactionFromLegacyToNativeSegwit.CreateStandardP2WPKHWithOneOutput
core/test/integration/http_cache/BitcoinMakeTransactionFromLegacyToP2WSH.CreateStandardP2WSHWithOneOutput
core/test/integration/http_cache/BitcoinMakeTransactionFromNativeSegwitToNativeSegwit.CreateStandardP2WPKHWithOneOutput
core/test/integration/http_cache/BitcoinMakeTransactionFromNativeSegwitToP2WSH.CreateStandardP2WSHWithOneOutput
core/test/integration/transactions/bitcoin_P2WPKH_transaction_tests.cpp
core/test/integration/transactions/bitcoin_P2WSH_transaction_tests.cpp
core/test/integration/transactions/coin_selection_P2PKH.cpp
core/test/integration/transactions/transaction_test_helper.cpp
core/test/integration/transactions/transaction_test_helper.h
core/test/tezos/tezos_account.cpp
core/test/tezos/transaction_test.hpp

- Adds CreateTransaction tests with P2WPKH and P2WSH outputs.
- Removes BitcoinLikeTransactionBuilder::addInput method (not used, probably incorrectly implemented).
- Fixes Tezos tests that require stable account id.

Add segwit tests

---

CMakeLists.txt
core/src/math/Base58.cpp
core/src/utils/DateUtils.cpp
core/src/wallet/bitcoin/explorers/BitcoinLikeBlockchainExplorer.hpp
core/src/wallet/bitcoin/explorers/api/InputParser.cpp
core/src/wallet/bitcoin/explorers/api/TransactionParser.cpp

* Fix a very specific weird crash that happens when loading the libcore from the Java runtime. It happens when initializing `std::regex` in static variables.  
* Fix btc transaction parsing when the explorer returns fees as string values (not integer). 
* Fix possible memory leak in Base58  (#859)
* Bump patch version to `4.1.6`
* [VG-3617](https://ledgerhq.atlassian.net/browse/VG-3617)

VG-3617: Fix some weird crash in wd integration tests

---

CMakeLists.txt
core/src/tezos/TezosLikeAddress.cpp
core/src/wallet/tezos/explorers/api/TezosLikeTransactionParser.cpp
core/test/coin-integration/stellar/horizon_explorer_tests.cpp

This PR addresses two defects, see References below.
* Tezos transaction parser now sets the value (and thus operation "amount") to 0 for (un)delegation operations
* Tezos transaction parser now sets the receiver to empty for undelegation operations. This allows one to differentiate delegation and undelegation: 
* delegation:  type `OPERATION_TAG_DELEGATION` and receiver is non-empty
* undelegation: type `OPERATION_TAG_DELEGATION` and receiver is empty
* Bump patch version to `4.1.7`
* [VG-3785 Wrong amount for delegate/undelegate txs for tezos](https://ledgerhq.atlassian.net/browse/VG-3785)
* [VG-3957 Undelegate transactions are not reconciled](https://ledgerhq.atlassian.net/browse/VG-3957)

[VG-3785] [VG-3957] Fix Tezos delegation amount and receiver

---

CMakeLists.txt
core/src/wallet/tezos/explorers/api/TezosLikeTransactionParser.cpp

* Fix the Tezos transaction parser to adapt to the new version of the tzstat API considering `delegation` operations. In particular:
* now a delegation operation has a `baker` field instead of a `delegate` field
* now a delegation withdraw operation has a `previous_baker`  field instead of a `receiver` field
* bump libcore version to `4.1.8`
* [VG-4357- All delegations and undelegations are shown with the "UNDELEGATE" icon on tx list (seems to be a gate issue)](https://ledgerhq.atlassian.net/browse/VG-4357)

VG-4357: Fix Tezos tx parser to handle new attributes from explorer

---

CMakeLists.txt
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp
core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp

* Fix incorrect conversions in gas price computation. This was due to incorrect locale set in the libcore, the fix consists to set the locale in function scope to make sure to use the correct character as decimal separator.
* Fix formula used to compute the gas price. The correct formula, [according to tzindex](https://github.com/blockwatch-cc/tzindex/blob/df40c4f3fc2887d1fff673a3369f069278e3447d/etl/op.go#L641), is to divide fee with gas_used and not gas_limit.
* Fix reveal fee formula used in tezos transaction crafter
* Bump patch version to `4.1.10`

VG-4576 Fix tezos reveal operation

---

CMakeLists.txt
core/idl/wallet/tezos/tezos_like_wallet.djinni
core/src/api/TezosLikeTransaction.hpp
core/src/jni/jni/TezosLikeTransaction.cpp
core/src/wallet/common/Operation.cpp
core/src/wallet/tezos/TezosLikeAccount2.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp
core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.h
core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.h
core/src/wallet/tezos/explorers/api/TezosLikeTransactionParser.cpp
core/src/wallet/tezos/transaction_builders/TezosLikeTransactionBuilder.cpp
core/test/common/operation.cpp
core/test/tezos/ED25519_transaction_test.cpp
core/test/tezos/P256_transaction_test.cpp
core/test/tezos/SECP256K1_transaction_test.cpp
core/test/tezos/tezos_account.cpp

An update of tzindex caused some breaking changes in Tezos node API. The following changes handle the breaking change in identifying batch operations. We implemented an operation uid based on `counter + txOpIndex` where `txOpIndex` is the index of the operation in the batch. This information is not directly available anymore. We decided to remove it from the computation of the operation uid.  
* Remove `index` from Tezos operations
* Remove `txOpIndex` from the Tezos operation uid computation
* Bump patch version to `4.1.11`

Remove txopindex from operationuid

---

CMakeLists.txt
core/src/database/DatabaseSessionPool.hpp
core/src/database/migrations.cpp
core/src/database/migrations.hpp

Improve performances when getting operations (`GET /pools/pool_name/wallets/wallet_name/accounts/acc_idx/operations?batch=300&full_op=1`) for big accounts

Add some index for transaction listing

---

CMakeLists.txt
core/src/wallet/tezos/TezosLikeAccount.h
core/src/wallet/tezos/delegation/TezosLikeOriginatedAccount.h

In `TezosLikeAccount::queryOperations()`, the TezosOperationQuery is built with a head filter based on the outer join with `tezos_originated_operations`, thus the generic performCount() request cannot be executed. As for `performExecute`, we need to override `performCount`
Should fix https://github.com/LedgerHQ/ledger-wallet-daemon/pull/476

Fix tezos count query

---

core/lib/sqlcipher/sqlite3.h
core/lib/sqlcipher/sqlite3ext.h
core/src/database/migrations.cpp

Update SQLite to the recent version.
Motivation: use the support of ALTER TABLE DROP COLUMN to simplify DB schema migration.
Here is the procedure I used to obtain these new files:
```
git clone https://github.com/sqlcipher/sqlcipher.git && cd sqlcipher
git checkout v4.5.1
mkdir bld && cd bld
../configure
make sqlite3.c
```

VG-5378 SQLite (sqlcipher) 3.26.0 -> 3.37.2

---

core/src/math/Base58.cpp
core/test/math/base58_test.cpp

Fix crash of WD when creating account with empty extended key

VG-737 Fix crash on base58 decode with empty string

---

.circleci/copy_artifacts.sh
.circleci/publish_jar.sh
README.md
tools/prod-like-build-inner.sh
tools/prod-like-build.sh

* builds Docker container from `LedgerHQ/lib-ledger-core-build-env`
* uses CircleCI scripts to build `ledger-lib-core.jar`
Attn: default paths to jre libraries are different in prod and on typical dev machine. `LD_LIBRARY_PATH` must be modified accordingly to run WD:
```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server sbt "run -http.port=:9200 -admin.port=:0"
```
This PR depends on https://github.com/LedgerHQ/lib-ledger-core-build-env/pull/9

Production-like build on dev PC

---

.github/workflows/nix_release_builds.yml
.github/workflows/release.yml
tools/set_version.sh

This is a manual workflow to be run from github action page (manual run will be available once PR is merged to `main`)
* Set given version in CMakeLists.txt
* Commit CMakeLists.txt
* Add tag to commit
* Create release note (can be manully disabled)
Here is example of Release generated by this workflow: https://github.com/LedgerHQ/lib-ledger-core/releases/tag/4.3.4-testReleaseWorkflow I will delete it as soon as we validate this PR

Add Release workflow

---

core/lib/soci/core/connection-pool.cpp
core/lib/soci/core/connection-pool.h
core/lib/soci/core/session.cpp
core/lib/soci/core/session.h
core/lib/soci/core/statement.cpp
core/src/database/DatabaseSessionPool.cpp

Due to concurrency on SessionTracer we had a core dump crash on runtime
This PR adds the ability to have multiple spans at a time in the same SessionTracer, and adds thread-safety on it

VG-9372 Fix sql session tracer

---

core/src/wallet/bitcoin/BitcoinLikeWallet.cpp
core/src/wallet/bitcoin/BitcoinLikeWallet.hpp

Because LAMA sync do not store all blocks in database, we need to ask explorer for last block

VG-10108 Fix get last block

---

core/src/utils/Cached.h
core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeUtxoPicker.cpp
core/src/wallet/cosmos/CosmosLikeAccount.cpp
core/src/wallet/ethereum/EthereumLikeAccount.cpp
core/src/wallet/ripple/RippleLikeAccount.cpp
core/src/wallet/stellar/StellarLikeAccount.cpp
core/src/wallet/tezos/TezosLikeAccount.cpp

Do not fetch keychain twice for the same address
Might fix VG-1215

Improve Get Balance History

---

core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
core/src/wallet/bitcoin/database/BitcoinLikeUTXODatabaseHelper.cpp
core/src/wallet/bitcoin/database/BitcoinLikeUTXODatabaseHelper.h

Use postgresql sum instead of useless fetching-all + ordering before summing in memory

Improve get balance time to compute

---

CMakeLists.txt
core/idl/wallet/bitcoin/bitcoin_like_wallet.djinni
core/src/api/BitcoinLikePickingStrategy.cpp
core/src/api/BitcoinLikePickingStrategy.hpp
core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
core/src/wallet/bitcoin/scripts/BitcoinLikeScript.cpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeStrategyUtxoPicker.cpp
core/src/wallet/bitcoin/transaction_builders/BitcoinLikeStrategyUtxoPicker.h
core/test/bitcoin/bitcoin_utxo_picket_tests.cpp
core/test/integration/transactions/coin_selection_P2PKH.cpp

This PR is intended to solve VG-10452.
* FeeIsEnoughFor{P2WPKH, P2WSH, P2TR} tests
* Fix for fee calculation in `OptimizeSize` strategy
* `highest_first_limit_utxo` and `limit_utxo` strategies are removed because aren't used by WD

Fix fee calculation for OptimizeSize UTXO picking strategy

---

core/idl/wallet/configuration.djinni
core/src/api/Configuration.cpp
core/src/api/Configuration.hpp
core/src/wallet/bitcoin/keychains/CommonBitcoinLikeKeychains.cpp
core/test/integration/keychains/common_bitcoin_keychain_test.cpp
core/test/integration/keychains/keychain_test_helper.h

Static receive & change address for regulated accounts

Add option to use static address

---

core/test/integration/http_cache/BitcoinMainNetMakeP2TRTransaction.CreateP2TRWithUnsupportedWitnessVersion
core/test/integration/transactions/bitcoin_P2TR_transaction_test.cpp

An additional test that verifies that we don't craft transaction with unsupported witness version.

Test that verifies that we don't create transactions with unsupported witness version

---

.github/workflows/tests.yml
core/src/database/DatabaseSessionPool.hpp
core/src/database/migrations.cpp
core/src/database/migrations.hpp
core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
core/src/wallet/bitcoin/database/BitcoinLikeUTXODatabaseHelper.cpp
core/src/wallet/bitcoin/database/BitcoinLikeUTXODatabaseHelper.h
core/src/wallet/bitcoin/synchronizers/BlockchainExplorerAccountSynchronizer.cpp

Read balance from cached value in bitcoin_accounts
If no cached balance available, compute it (as before)
-> Balance in written by https://github.com/LedgerHQ/lama-bitcoin/pull/566
VG-13107

VG-13107 feat(BTC): Use cached balance on bitcoin accounts

---

core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.cpp
core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.h
core/src/wallet/ripple/explorers/api/RippleLikeTransactionParser.cpp

Fixes [VSD-2389](https://ledgerhq.atlassian.net/browse/VSD-2389) and [VSD-2405](https://ledgerhq.atlassian.net/browse/VSD-2405)
Changes: 
- `ledger_index_min` is now returned as a integer object and not a string-integer ; the synchronization fails at fetching the account transactions. Fix: change `ledger_index_min` type from string to unsigned int64 
- `Amount` attribute is missing for `AccountDelete` tx type. Fix: parse `DeliveredAmount`, which is there for this tx type instead. 
Note: I would not suggest to use `delivered_amount` which seems always returned because I don't know how the parsing would go for other tx types, e.g. if `delivered_amount` is always matching `Amount` (even if I suppose they will be always equal). 
Results:
sync successful, no error at sync, correct amount saved …

Fix ripple explorer (de)serialization issues
