LedgerHQ/lib-ledger-core

core/src/crypto/AESCipher.cpp, core/src/crypto/AESCipher.hpp, core/src/database/SQLite3Backend.cpp, core/src/database/query/QueryBuilder.cpp, core/src/database/query/QueryBuilder.h, core/src/events/EventBus.cpp, core/src/wallet/common/AbstractWallet.cpp, core/src/wallet/common/AbstractWallet.hpp, core/src/wallet/common/OperationQuery.cpp, core/test/crypto/encryption_test.cpp, core/test/database/query_builder_tests.cpp, core/test/events/events_test.cpp, core/test/integration/synchronization_tests.cpp, core/test/integration/wallet_database_tests.cpp
- Fix test **ledger-core-database-tests**: test dangling to fix pass weak pointers to Future::async methods in EventBus class,
- Fix test **ledger-core-integration-tests**: test dangling to fix: pass weak pointers (receivers) to lambdas passed to Future::async methods in EventBus class and fixed some SQL queries,
- Fix test **ledger-core-crypto-tests**: random fail in EncryptDecryptWithCipeherHugeText because parasite character appearing when streaming with stringstream
=> Fixes tests : database, integration and crypto

core/src/async/Future.hpp, core/src/events/EventBus.cpp, core/src/events/EventBus.hpp, core/src/wallet/bitcoin/BitcoinLikeWallet.cpp
Fix bad allocation during account creation.
=> Fix bad alloc

api/core/java/Account.java, api/core/nodejs/NJSAccountCpp.cpp, api/core/nodejs/NJSAccountCpp.hpp, api/core/nodejs/ledgerapp_nodejs_doc.js, api/core/objc/LGAccount.h, api/core/objcpp/LGAccount+Private.mm, api/core/react-native/LibLedgerCore/ios/Sources/RCTCoreLGAccount.m, core/idl/wallet/common/wallet.djinni, core/src/api/Account.hpp, core/src/bitcoin/BitcoinLikeExtendedPublicKey.cpp, core/src/database/soci-number.h, core/src/jni/jni/Account.cpp, core/src/utils/DerivationPath.cpp, core/src/utils/DerivationPath.hpp, core/src/wallet/bitcoin/BitcoinLikeAccount.cpp, core/src/wallet/bitcoin/BitcoinLikeAccount.hpp, core/src/wallet/bitcoin/api_impl/BitcoinLikeTransactionApi.cpp, core/src/wallet/bitcoin/explorers/BitcoinLikeBlockchainExplorer.hpp, core/src/wallet/bitcoin/explorers/LedgerApiBitcoinLikeBlockchainExplorer.cpp, core/src/wallet/bitcoin/keychains/BitcoinLikeKeychain.cpp, core/src/wallet/bitcoin/networks.cpp, core/src/wallet/bitcoin/synchronizers/BlockchainExplorerAccountSynchronizer.cpp, core/src/wallet/bitcoin/transaction_builders/BitcoinLikeUtxoPicker.cpp, core/src/wallet/pool/database/CurrenciesDatabaseHelper.cpp, core/test/crypto/digest_test.cpp, core/test/integration/bitcoin_transaction_tests.cpp, core/test/integration/synchronization_tests.cpp, qt-host/async/QtMainExecutionContext.hpp
- Fix a bug to push transactions
- Add getRestoreKey
- Small crash fixes
=> Small fixes

.circleci/build_node_module.sh, .circleci/config.yml, appveyor.yml, core/src/wallet/common/database/AccountDatabaseHelper.cpp, tools/build_ios/ios_build.sh, tools/build_ios/iphone.cmake
- Use Xcode 10 for MacOS CI,
- Remove Appveyor deploy step and use aws cli instead,
- Fix AccountDatabaseHelper to fix: [https://github.com/LedgerHQ/ledger-live-desktop/pull/1609](url)
=> CI improvements

CMakeLists.txt, appveyor.yml, core/src/wallet/bitcoin/BitcoinLikeAccount.cpp, core/src/wallet/bitcoin/api_impl/BitcoinLikeTransactionApi.cpp, core/src/wallet/bitcoin/api_impl/BitcoinLikeTransactionApi.h, core/src/wallet/bitcoin/api_impl/BitcoinLikeWritableInputApi.cpp, core/src/wallet/bitcoin/api_impl/BitcoinLikeWritableInputApi.h, core/src/wallet/bitcoin/scripts/BitcoinLikeScript.cpp, core/src/wallet/bitcoin/scripts/BitcoinLikeScript.h, core/src/wallet/common/database/OperationDatabaseHelper.cpp, core/test/integration/transactions/bitcoin_P2PKH_transaction_tests.cpp, core/test/integration/transactions/bitcoin_P2SH_transaction_tests.cpp
- Implement parsing of signed raw transactions,
- Implement parsing of signed scripts,
- Optimistic update is now using `parseSignedTransaction` (this should fix issues related to LLC-56)
=> Preparing for 1.1.5

core/src/async/FutureUtils.hpp, core/test/async/future_test.cpp, core/test/lib/libledger-test/TempDir.hpp
To be able to schedule something when all given Futures complete.
=> Add executeAll functions

core/src/wallet/BalanceService.hpp, core/src/wallet/bitcoin/BalanceServiceUTXOBased.cpp, core/src/wallet/bitcoin/BalanceServiceUTXOBased.hpp, core/test/wallet/BalanceServiceUTXOBased_test.cpp, core/test/wallet/CMakeLists.txt, core/test/wallet/Mocks.hpp
Interface, implementation based on UTXOService and tests added
=> Add BalanceService

core/src/debug/LoggerApi.hpp, core/src/debug/logger.cpp, core/src/debug/logger.hpp, core/src/wallet/pool/WalletPool.cpp, core/src/wallet/pool/WalletPool.hpp
=> Add the possibility to switch off spdlog.

core/src/debug/LoggerApi.hpp, core/src/debug/logger.cpp, core/src/debug/logger.hpp, core/src/wallet/pool/WalletPool.cpp, core/src/wallet/pool/WalletPool.hpp
This reverts commit ce1435e48abf94c0852e7469db38cdeee45492d6.
=> Revert "Add the possibility to switch off spdlog."

.circleci/build_lib.sh, .circleci/cmake-install.sh, .circleci/config.yml
Looks like it works now for macos and linux
=> Fast cmake

core/src/CMakeLists.txt
=> Fix versioning

tools/generateBindings.sh
In order to take into account new djinni version
=> Update djinni, generateBindings script changes

CMakeLists.txt, appveyor.yml, core/idl/preferences/preferences.djinni, core/idl/wallet/wallet_pool.djinni, core/src/api/PreferencesEditor.hpp, core/src/api/WalletPool.hpp, core/src/database/DatabaseBackend.hpp, core/src/database/DatabaseSessionPool.cpp, core/src/database/DatabaseSessionPool.hpp, core/src/database/migrations.cpp, core/src/database/migrations.hpp, core/src/jni/jni/PreferencesEditor.cpp, core/src/jni/jni/WalletPool.cpp, core/src/preferences/PreferencesBackend.cpp, core/src/preferences/PreferencesBackend.hpp, core/src/preferences/PreferencesEditor.cpp, core/src/preferences/PreferencesEditor.hpp, core/src/wallet/bitcoin/factories/BitcoinLikeWalletFactory.cpp, core/src/wallet/pool/WalletPool.cpp, core/src/wallet/pool/WalletPool.hpp, core/src/wallet/pool/api/WalletPoolApi.cpp, core/src/wallet/pool/api/WalletPoolApi.hpp, core/test/integration/CMakeLists.txt, core/test/integration/synchronization/synchronization_tests.cpp, core/test/preferences/preferences_test.cpp
=> Add freshResetAll to reset libcore to a “fresh install”-like state

playground/Dockerfile, playground/README.md, playground/install_nvm.sh, playground/manage
=> Add the docker playground. [skip ci]

core/idl/bitcoin/addresses.djinni, core/idl/collections/dynamic.djinni, core/idl/crypto/crypto.djinni, core/idl/crypto/secp256k1.djinni, core/idl/database/database.djinni, core/idl/debug/logger.djinni, core/idl/ethereum/addresses.djinni, core/idl/events/emitter.djinni, core/idl/events/events.djinni, core/idl/math/big_int.djinni, core/idl/math/random.djinni, core/idl/net/http_client.djinni, core/idl/net/websocket_client.djinni, core/idl/networks.djinni, core/idl/preferences/preferences.djinni, core/idl/utils/callback.djinni, core/idl/wallet/bitcoin/bitcoin_like_wallet.djinni, core/idl/wallet/bitcoin/bitcoin_script.djinni, core/idl/wallet/common/currency.djinni, core/idl/wallet/common/wallet.djinni
I might open several PRs for that as it has no impact but documentation.
=> First pass of fixing and documenting the IDL files.

README.md
[Rendered.](https://github.com/phaazon/lib-ledger-core/tree/misc/document-osx-upgrade#qa-and-troubleshooting)
=> Provide some hints about questions/answers and macOSX upgrading.

CHANGELOG.md, core/idl/wallet/wallet_pool.djinni, core/src/api/WalletPool.hpp, core/src/wallet/pool/WalletPool.cpp, core/src/wallet/pool/WalletPool.hpp, core/src/wallet/pool/api/WalletPoolApi.cpp
Also, support preferences backend password change.
=> Move password change implementation from the API interface to the WalletPool implementation.

core/idl/wallet/ethereum/ethereum_like_wallet.djinni, core/src/api/EthereumLikeTransaction.hpp, core/src/jni/jni/EthereumLikeTransaction.cpp, core/src/wallet/ethereum/api_impl/EthereumLikeTransactionApi.cpp, core/src/wallet/ethereum/api_impl/EthereumLikeTransactionApi.h
- Once merged, I will re-generate bindings and submit corresponding PRs to repos
=> Add getStatus method on EthereumLikeTransaction

core/src/wallet/ethereum/database/EthereumLikeTransactionDatabaseHelper.cpp
=> Fix ETH transaction details in ETH operations

core/src/wallet/common/explorers/AbstractLedgerApiBlockchainExplorer.h, core/src/wallet/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.cpp
Meh ! 
This fix was provided in to allow a production deployment !
=> ETH: Fix case issue on call to explorers

core/src/bitcoin/bech32/Bech32Parameters.cpp, core/src/database/migrations.hpp, core/src/wallet/bitcoin/BitcoinLikeAccount.cpp, core/src/wallet/bitcoin/database/BitcoinLikeTransactionDatabaseHelper.cpp, core/src/wallet/common/database/AccountDatabaseHelper.cpp, core/src/wallet/common/database/OperationDatabaseHelper.cpp, core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp, core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/src/wallet/ethereum/database/EthereumLikeTransactionDatabaseHelper.cpp, core/src/wallet/pool/database/CurrenciesDatabaseHelper.cpp, core/src/wallet/pool/database/PoolDatabaseHelper.cpp, core/src/wallet/ripple/RippleLikeAccount.cpp, core/src/wallet/ripple/database/RippleLikeTransactionDatabaseHelper.cpp
Argument of use() shouldn't be temporaly object.
=> Fix soci usages

.circleci/build_lib.sh, .circleci/config.yml
To not use libncurses during building
and to apply recent bugfixes.
=> Update Android NDK

core/test/preferences/preferences_test.cpp
=>  Fix PreferencesBackend password change (empty new passwords now disable encryption).

core/idl/wallet/ethereum/erc20.djinni, core/src/api/ERC20LikeOperation.hpp, core/src/api/RippleLikeMemo.hpp, core/src/jni/jni/ERC20LikeOperation.cpp, core/src/wallet/ethereum/ERC20/ERC20LikeOperation.cpp, core/src/wallet/ethereum/ERC20/ERC20LikeOperation.h, core/test/integration/synchronization/ethereum_synchronization.cpp
Related issue : https://ledgerhq.atlassian.net/browse/LLC-210
=> Add getBlockHeight method on erc20 operations

core/src/wallet/pool/WalletPool.cpp, core/test/integration/BaseFixture.cpp, core/test/integration/BaseFixture.h, core/test/integration/account_creation_tests.cpp
changing password from empty to non-empty password was crashing the app ...
=> Fix encryption

core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp, core/src/wallet/ethereum/ERC20/ERC20LikeOperation.cpp, core/src/wallet/ethereum/ERC20/ERC20LikeOperation.h, core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/src/wallet/ethereum/explorers/EthereumLikeBlockchainExplorer.h, core/src/wallet/ethereum/explorers/api/EthereumLikeTransactionParser.cpp
Support multiple transfer events under same ETH transaction, this might be the case with DEXes
=> Handle multiple ERC20 transfer events in same ETH transaction

core/src/database/DatabaseSessionPool.hpp, core/src/database/migrations.cpp, core/src/database/migrations.hpp
Small fixes due to the fact we are using sqlite to test. Sqlite doesn't care about types it just save all strings type as TEXT but other RDBMS do care.
=> Fix core library when using PGSQL

core/idl/wallet/common/wallet.djinni, core/src/api/OperationType.cpp, core/src/api/OperationType.hpp, core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp, core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/src/wallet/ethereum/EthereumLikeAccount.h, core/src/wallet/ripple/RippleLikeAccount.cpp
Handle transactions not belonging to ETH account that creates transfer events related to current synchronizing ETH account
=> Fix Ethereum: ERC20 balance

core/src/utils/DerivationScheme.cpp, core/src/wallet/ethereum/keychains/EthereumLikeKeychain.cpp, core/test/integration/BaseFixture.cpp, core/test/integration/BaseFixture.h, core/test/integration/keychains/ethereum_keychain_test.cpp, core/test/integration/synchronization/ethereum_synchronization.cpp
Live is supporting some weird derivation paths as: `44'/60'/14'/5'/16`, `44'/60'/0'/0' ...`
=> Support exotic derivation paths

.circleci/build_lib.sh
Related to : https://ledgerhq.atlassian.net/browse/LLC-219
=> Change x86 android toolchain to x86_64 one

core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/src/wallet/ethereum/EthereumLikeAccount.h, core/src/wallet/ethereum/EthereumLikeWallet.cpp, core/src/wallet/ethereum/database/EthereumLikeAccountDatabaseEntry.h, core/src/wallet/ethereum/database/EthereumLikeAccountDatabaseHelper.cpp, core/src/wallet/ethereum/database/EthereumLikeAccountDatabaseHelper.h, core/test/integration/BaseFixture.cpp, core/test/integration/synchronization/ethereum_synchronization.cpp
Related to : https://ledgerhq.atlassian.net/browse/LLC-233
=> Fix ETH: recovery of ERC20 accounts from DB

core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/test/integration/transactions/ethereum_transaction_tests.cpp
Related to : https://ledgerhq.atlassian.net/browse/LLC-246
=> Check ETH balance when building an ETH transaction

.circleci/config.yml, .circleci/setup_debian.sh
This reverts commit b108d844799f134470a67834a8956fcc263eeb8c.
=> Revert "Change debian to buster, to have new default gcc"

.circleci/setup_debian.sh
=> Install openjdk8 on Debian/Stretch

core/src/database/migrations.cpp, core/test/integration/synchronization/ethereum_synchronization.cpp
Related to : https://ledgerhq.atlassian.net/browse/LLC-251
=> Fix ETH foreign key failing constraint when calling freshResetAll

core/src/ethereum/EthereumLikeAddress.cpp, core/src/ethereum/EthereumLikeAddress.h, core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp, core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/src/wallet/ethereum/EthereumLikeAccount.h, core/src/wallet/ethereum/database/EthereumLikeTransactionDatabaseHelper.cpp, core/src/wallet/ethereum/explorers/EthereumLikeBlockchainExplorer.h, core/test/integration/transactions/ethereum_transaction_tests.cpp
This is related to : https://ledgerhq.atlassian.net/browse/LLC-264
=> Implement optimistic update for ETH

core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp, core/src/wallet/ethereum/database/EthereumLikeTransactionDatabaseHelper.cpp
=> Fix typos on ETH database update calls

CMakeLists.txt, appveyor.yml, core/idl/wallet/ethereum/erc20.djinni, core/idl/wallet/ethereum/ethereum_like_wallet.djinni, core/src/api/ERC20LikeAccount.hpp, core/src/api/EthereumLikeAccount.hpp, core/src/api/EthereumLikeBlock.hpp, core/src/api/RippleLikeAccount.hpp, core/src/api/RippleLikeBlock.hpp, core/src/jni/jni/ERC20LikeAccount.cpp, core/src/jni/jni/EthereumLikeAccount.cpp, core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp, core/src/wallet/ethereum/ERC20/ERC20LikeAccount.h, core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/src/wallet/ethereum/EthereumLikeAccount.h, core/src/wallet/ethereum/EthereumLikeWallet.cpp, core/src/wallet/ethereum/explorers/EthereumLikeBlockchainExplorer.h, core/src/wallet/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.cpp, core/src/wallet/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.h, core/test/integration/synchronization/ethereum_synchronization.cpp, qt-host/net/QtHttpClient.cpp
Rely on call to `balanceOf` of erc20 contracts instead of local operations (because we might miss some tricky ops ...)
=> Erc20 balance

core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/test/integration/synchronization/ethereum_synchronization.cpp
I added the tests to `synchronization` and not `transactions` because account in the latest does not have a balance.
**TODO (later)**: we should get a test account from QA with (>0) balance and get all infos (like xpub, pubKey, chainCode ...) and use it in `transactions` tests ! 
This is related to : https://ledgerhq.atlassian.net/browse/LLC-281
=> Implement wipeToaddress method on ETH

core/src/wallet/ripple/RippleLikeWallet.cpp, core/test/integration/account_info_test.cpp
This is related to : https://ledgerhq.atlassian.net/browse/LLC-241
=> Fix XRP getAccountCreationInfo method

core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/src/wallet/ethereum/EthereumLikeAccount.h
I moved same code to a new method `updateERC20Operation` 
Related to: https://ledgerhq.atlassian.net/browse/LLC-265
=> Fix ERC20: insert correctly self operations

core/src/wallet/ethereum/api_impl/EthereumLikeTransactionApi.cpp
Related to : https://ledgerhq.atlassian.net/browse/LL-1526
=> Remove leading zeros from eth R and S fields

core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp, core/src/wallet/ethereum/database/EthereumLikeTransactionDatabaseHelper.cpp
Related to : https://ledgerhq.atlassian.net/browse/LLC-286
=> Refresh used gas once tx is mined

core/src/wallet/ethereum/EthereumLikeAccount.cpp
Related to : https://ledgerhq.atlassian.net/browse/LL-1607
=> Set gasUsed for optimistic update

core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.cpp, core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.h
Related to : https://ledgerhq.atlassian.net/browse/LLC-296
=> Fix XRP: explorer methods should handle non existing accounts

.circleci/publish_jar.sh
test passed at @KhalilBellakrid 's branch
=> fix publish jar

core/src/database/migrations.cpp, core/src/wallet/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.cpp
Related to : https://ledgerhq.atlassian.net/browse/LLC-303
=> Fix ETH explorer: add ticker to endpoint to query ERC20 balances

core/src/utils/DerivationScheme.cpp, core/src/utils/DerivationScheme.hpp, core/src/wallet/ripple/RippleLikeWallet.cpp, core/src/wallet/ripple/keychains/RippleLikeKeychain.cpp, core/test/integration/BaseFixture.cpp, core/test/integration/keychains/ripple_keychain_test.cpp
Related to : https://ledgerhq.atlassian.net/browse/LLC-299
=> Fix XRP to support exotic/legacy Live paths

CHANGELOG.md, CMakeLists.txt, appveyor.yml, core/idl/wallet/bitcoin/bitcoin_like_wallet.djinni, core/src/api/BitcoinLikeOutput.hpp, core/src/api/InternalTransaction.hpp, core/src/database/DatabaseSessionPool.hpp, core/src/database/migrations.cpp, core/src/database/migrations.hpp, core/src/jni/jni/BitcoinLikeOutput.cpp, core/src/wallet/bitcoin/api_impl/BitcoinLikeOutputApi.cpp, core/src/wallet/bitcoin/api_impl/BitcoinLikeOutputApi.h, core/src/wallet/bitcoin/database/BitcoinLikeTransactionDatabaseHelper.cpp, core/src/wallet/bitcoin/database/BitcoinLikeUTXODatabaseHelper.cpp, core/src/wallet/bitcoin/explorers/BitcoinLikeBlockchainExplorer.hpp, core/src/wallet/bitcoin/explorers/api/TransactionParser.cpp, core/src/wallet/bitcoin/transaction_builders/BitcoinLikeStrategyUtxoPicker.cpp, core/src/wallet/bitcoin/transaction_builders/BitcoinLikeStrategyUtxoPicker.h
This is related to : https://ledgerhq.atlassian.net/browse/LLC-301
=> Improve UTXO picking strategy DEEP_OUTPUTS_FIRST performances

core/test/integration/CMakeLists.txt, core/test/integration/synchronization/ethereum_synchronization.cpp, core/test/lib/libledger-test/CMakeLists.txt, core/test/lib/libledger-test/FakeHttpClient.cpp, core/test/lib/libledger-test/FakeHttpClient.hpp, core/test/lib/libledger-test/FakeUrlConnection.cpp, core/test/lib/libledger-test/FakeUrlConnection.hpp
Add test about synchronization reorg.
=> Reorg test

core/src/utils/hex.cpp
On response of https://github.com/LedgerHQ/lib-ledger-core/issues/284
=> Include <stdexcept> to fix MSVC2019 build issue

core/src/wallet/ripple/RippleLikeAccount.cpp, core/src/wallet/ripple/explorers/ApiRippleLikeBlockchainExplorer.cpp, core/src/wallet/ripple/explorers/ApiRippleLikeBlockchainExplorer.h, core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.cpp, core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.h, core/src/wallet/ripple/explorers/RippleLikeBlockchainExplorer.h, core/test/integration/transactions/ripple_transaction_tests.cpp
=> XRP fixes for Sequence and LastLedgerSequence when building transaction

core/src/preferences/PreferencesBackend.cpp, core/src/preferences/PreferencesBackend.hpp
Instead of having a non-owning unordered_map and lots of owning
`shared_ptr` everywhere in the codebase, we now have an owning table and
weak_ptr everywhere. The idea is that, if we get a
`shared_ptr<ledger::core::PreferencesBackend>`, the underlying database is
handled via a weak_ptr. Which means that you have to lock it in order to
use the database, which allows us to destroy the database and observe it
everywhere.
Fixes LLC-198
=> Changed the ownership mechanism of LevelDB in PreferencesBackend.

core/idl/wallet/common/wallet.djinni, core/src/api/Account.hpp, core/src/jni/jni/Account.cpp, core/src/wallet/common/AbstractAccount.cpp, core/src/wallet/common/AbstractAccount.hpp
=> Add asTezosLikeAccount.

core/src/wallet/ripple/RippleLikeWallet.cpp, core/src/wallet/tezos/TezosLikeWallet.cpp
=> Fix *Wallet::type.

core/src/wallet/ripple/database/RippleLikeTransactionDatabaseHelper.cpp
Bug found by @gre. May he have a cookie (thanks!).
=> Fix XRP database missing column when inserting transactions.

core/src/wallet/ripple/database/RippleLikeTransactionDatabaseHelper.cpp
=> Fix Dynamic exception bad cast on XRP.

core/src/wallet/ripple/database/RippleLikeTransactionDatabaseHelper.cpp
Reported by @onyb. SInce I re-enabled the CI checks, we shouldn’t have that kind of problems anymore.
=> Fix Linux issue with BigInt explicit ctor.

core/src/wallet/ethereum/database/EthereumLikeTransactionDatabaseHelper.cpp, core/src/wallet/ethereum/explorers/api/EthereumLikeTransactionParser.cpp, core/test/integration/synchronization/ethereum_synchronization.cpp
This relates to [LLC-341](https://ledgerhq.atlassian.net/browse/LLC-341)
=> Fix Linux bug: nonce returned by explorer is in a decimal format instead of hexadecimal

core/idl/wallet/tezos/tezos_like_wallet.djinni, core/src/api/TezosLikeTransaction.hpp, core/src/jni/jni/TezosLikeTransaction.cpp, core/src/tezos/TezosLikeAddress.cpp, core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp, core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.h, core/src/wallet/tezos/transaction_builders/TezosLikeTransactionBuilder.cpp, core/test/integration/transactions/tezos_transaction_tests.cpp, core/test/tezos/address_test.cpp
2 Fixes for Tezos integration:
- Fix validation of Tezos addresses,
- Fix signature parsing and serialization for Tezos transactions.
This PR is related to [LLC-356](https://ledgerhq.atlassian.net/browse/LLC-356) and [LLC-355](https://ledgerhq.atlassian.net/browse/LLC-355).
=> Tezos fixes

ledger-core/idl/address.djinni
These static methods should be implemented in coin library now
=> Remove coin-related static method 

core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.cpp
=> Consider txn submission with status terQUEUED as successful

core/src/database/DatabaseSessionPool.hpp, core/src/database/migrations.cpp, core/src/database/migrations.hpp, core/src/wallet/ripple/api_impl/RippleLikeTransactionApi.cpp, core/src/wallet/ripple/database/RippleLikeTransactionDatabaseHelper.cpp, core/src/wallet/ripple/explorers/RippleLikeBlockchainExplorer.h, core/src/wallet/ripple/explorers/api/RippleLikeTransactionParser.cpp, core/test/integration/BaseFixture.cpp, core/test/integration/BaseFixture.h, core/test/integration/synchronization/ripple_synchronization.cpp
Reopening #328 here. Between rebases and merging of #333, something weird happened, and it seems that #328 was finally not merged to `develop`.
=> Implement parsing of DestinationTag during Ripple account sync

core/src/wallet/ripple/explorers/api/RippleLikeTransactionParser.cpp, core/test/integration/synchronization/ripple_synchronization.cpp
There’s currently a bug with the date set to epoch.
=> Fix XRP date set to epoch.

ledger-core/inc/core/explorers/AbstractBlockParser.hpp, ledger-core/inc/core/explorers/LedgerApiParser.hpp, ledger-core/inc/core/synchronizers/AbstractBlockchainExplorerAccountSynchronizer.hpp
This PR contains also a small fix concerning a bad assignment.
=> `Block` to `api::block`

core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp, core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.h, core/src/wallet/tezos/explorers/api/TezosLikeBlockParser.h
Fix block height and time when using Tzstats, 
Fix balance: Tzstats can return floats or integers when querying balance.
=> Tezos: Fixes on Tzstats integration

core/src/wallet/bitcoin/transaction_builders/BitcoinLikeStrategyUtxoPicker.cpp
Fix targetted value in filterWithOptimizeSize by updating value with fees of collected/dropped UTXOs.
=> Bitcoin: fix fees when using OPTIMIZE_SIZE UTXO picking strategy 

core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp
I've tried with Live's CLI and it's working 🚀 : https://tzstats.com/oo6mPR9oNjzPsZNAMpmkjjKidWZxAo5s88wEN3KKbCvwB9yNCVH
=> Tezos: fix undelegation

ledger-core/inc/core/crypto/BLAKE.hpp, ledger-core/src/core/crypto/BLAKE.cpp, ledger-core/src/core/crypto/DeterministicPublicKey.cpp
=> (RE)add `blake2b` feature

ledger-core/inc/core/bytes/Zarith.hpp, ledger-core/src/core/bytes/Zarith.cpp
=> Zarith class 

core/src/wallet/pool/WalletPool.cpp
=> Cache WalletPool::getWallet.

core/idl/tezos/addresses.djinni, core/idl/wallet/tezos/tezos_like_wallet.djinni, core/src/api/TezosConfigurationDefaults.cpp, core/src/api/TezosConfigurationDefaults.hpp, core/src/api/TezosCurve.cpp, core/src/api/TezosCurve.hpp, core/src/tezos/TezosLikeAddress.cpp, core/src/tezos/TezosLikeAddress.h, core/src/tezos/TezosLikeExtendedPublicKey.cpp, core/src/wallet/tezos/TezosLikeAccount2.cpp, core/src/wallet/tezos/keychains/TezosLikeKeychain.cpp, core/src/wallet/tezos/transaction_builders/TezosLikeTransactionBuilder.cpp, core/test/integration/synchronization/tezos_synchronization.cpp, core/test/integration/transactions/tezos_transaction_tests.cpp, core/test/tezos/address_test.cpp
This relates to : https://ledgerhq.atlassian.net/browse/LLC-423
Note: Tested with Live and it's working ! 👍
=> Tezos: support tz3 addresses (P256 elliptic curve)

ledger-core/inc/core/net/HttpClient.hpp, ledger-core/src/core/net/HttpClient.cpp
=> Segregate HttpClient fix for tezos purpose 

ledger-core-ethereum/inc/ethereum/operations/EthereumLikeOperation.hpp, ledger-core-ethereum/src/ethereum/operations/EthereumLikeOperation.cpp, ledger-core-ripple/inc/ripple/RippleLikeOperation.hpp, ledger-core-ripple/src/ripple/RippleLikeOperation.cpp, ledger-core/inc/core/operation/Operation.hpp
=> Segregate Operation changes for XTZ purpose

CHANGELOG.md, CMakeLists.txt, appveyor.yml, core/idl/wallet/ethereum/ethereum_like_wallet.djinni, core/src/api/EthereumLikeAccount.hpp, core/src/jni/jni/EthereumLikeAccount.cpp, core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/src/wallet/ethereum/EthereumLikeAccount.h, core/src/wallet/ethereum/explorers/EthereumLikeBlockchainExplorer.h, core/src/wallet/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.cpp, core/src/wallet/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.h, core/test/integration/synchronization/ethereum_synchronization.cpp
Implement `getERC20Balances` to get balances of given ERC20 accounts
Related to: https://ledgerhq.atlassian.net/browse/LLC-393
=> Ethereum: Batch ERC20 balance queries

ledger-core-tezos/idl/addresses.djinni, ledger-core-tezos/idl/configuration.djinni, ledger-core-tezos/idl/idl.djinni, ledger-core-tezos/inc/tezos/TezosLikeAddress.hpp, ledger-core-tezos/inc/tezos/database/Migrations.hpp, ledger-core-tezos/inc/tezos/explorers/ExternalTezosLikeBlockchainExplorer.hpp, ledger-core-tezos/inc/tezos/explorers/NodeTezosLikeBlockchainExplorer.hpp, ledger-core-tezos/inc/tezos/explorers/TezosLikeBlockParser.hpp, ledger-core-tezos/inc/tezos/explorers/TezosLikeBlockchainExplorer.hpp, ledger-core-tezos/inc/tezos/explorers/TezosLikeTransactionsBulkParser.hpp, ledger-core-tezos/inc/tezos/operations/TezosLikeOperation.hpp, ledger-core-tezos/inc/tezos/transactions/TezosLikeTransaction.hpp, ledger-core-tezos/inc/tezos/transactions/TezosLikeTransactionBuilder.hpp, ledger-core-tezos/src/tezos/TezosLikeAccount.cpp, ledger-core-tezos/src/tezos/TezosLikeAccount2.cpp, ledger-core-tezos/src/tezos/TezosLikeAddress.cpp, ledger-core-tezos/src/tezos/TezosLikeExtendedPublicKey.cpp, ledger-core-tezos/src/tezos/database/Migrations.cpp, ledger-core-tezos/src/tezos/database/TezosLikeTransactionDatabaseHelper.cpp, ledger-core-tezos/src/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp, ledger-core-tezos/src/tezos/explorers/NodeTezosLikeBlockchainExplorer.cpp, ledger-core-tezos/src/tezos/explorers/TezosLikeBlockchainExplorer.cpp, ledger-core-tezos/src/tezos/explorers/TezosLikeTransactionParser.cpp, ledger-core-tezos/src/tezos/factories/TezosLikeWalletFactory.cpp, ledger-core-tezos/src/tezos/keychains/TezosLikeKeychain.cpp, ledger-core-tezos/src/tezos/operations/TezosLikeOperation.cpp, ledger-core-tezos/src/tezos/transactions/TezosLikeTransaction.cpp, ledger-core-tezos/src/tezos/transactions/TezosLikeTransactionBuilder.cpp
This PR embeds all the latest XTZ fixes in an exhaustive way.
**Disclaimer**: Maybe some stuff are missing but still we don't have XTZ tests, we cannot properly check if all are here.
=> Segregate all the latest XTZ fixes

CHANGELOG.md, CMakeLists.txt, appveyor.yml, core/src/wallet/bitcoin/BitcoinLikeAccount.cpp, core/src/wallet/bitcoin/factories/BitcoinLikeWalletFactory.cpp, core/src/wallet/bitcoin/transaction_builders/BitcoinLikeStrategyUtxoPicker.cpp, core/src/wallet/common/AbstractAccount.cpp, core/src/wallet/common/AbstractAccount.hpp, core/src/wallet/common/AbstractWallet.cpp, core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp, core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/src/wallet/ethereum/api_impl/EthereumLikeOperation.cpp, core/src/wallet/ethereum/api_impl/EthereumLikeOperation.h, core/src/wallet/ethereum/factories/EthereumLikeWalletFactory.cpp, core/src/wallet/pool/WalletPool.cpp, core/src/wallet/pool/WalletPool.hpp, core/src/wallet/ripple/RippleLikeAccount.cpp, core/src/wallet/ripple/factories/RippleLikeWalletFactory.cpp, core/src/wallet/tezos/TezosLikeAccount.cpp, core/src/wallet/tezos/TezosLikeAccount2.cpp, core/src/wallet/tezos/delegation/TezosLikeOriginatedAccount.cpp, core/src/wallet/tezos/factories/TezosLikeWalletFactory.cpp
Better usage of execution contexts.
**TODO:** 
- Additional Tests: I've already tested and now no task is blocked, but we should perform more QA in case we missed some blocking tasks,
=> Review execution context usage

CHANGELOG.md, CMakeLists.txt, appveyor.yml, core/idl/wallet/configuration.djinni, core/src/api/Configuration.cpp, core/src/api/Configuration.hpp, core/src/api/ConfigurationDefaults.cpp, core/src/api/ConfigurationDefaults.hpp, core/src/utils/TTLCache.h, core/src/wallet/bitcoin/BitcoinLikeAccount.cpp, core/src/wallet/bitcoin/factories/BitcoinLikeWalletFactory.cpp, core/src/wallet/bitcoin/transaction_builders/BitcoinLikeStrategyUtxoPicker.cpp, core/src/wallet/common/AbstractAccount.cpp, core/src/wallet/common/AbstractAccount.hpp, core/src/wallet/common/AbstractWallet.cpp, core/src/wallet/common/AbstractWallet.hpp, core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp, core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/src/wallet/ethereum/api_impl/EthereumLikeOperation.cpp, core/src/wallet/ethereum/api_impl/EthereumLikeOperation.h, core/src/wallet/ethereum/factories/EthereumLikeWalletFactory.cpp, core/src/wallet/pool/WalletPool.cpp, core/src/wallet/pool/WalletPool.hpp, core/src/wallet/ripple/RippleLikeAccount.cpp, core/src/wallet/ripple/factories/RippleLikeWalletFactory.cpp, core/src/wallet/tezos/TezosLikeAccount.cpp, core/src/wallet/tezos/TezosLikeAccount2.cpp, core/src/wallet/tezos/delegation/TezosLikeOriginatedAccount.cpp, core/src/wallet/tezos/factories/TezosLikeWalletFactory.cpp
Implementation of a simple cache to keep some values that are queried multiple times, here balance and last block.
=> Basic caching

ledger-core/idl/core.djinni, ledger-core/idl/tuples.djinni
=> Add missing djinni file for BTC

tools/lc
=> Fix wrong symlink 

ledger-core/inc/core/Services.hpp, ledger-core/inc/core/wallet/WalletStore.hpp, ledger-core/src/core/Services.cpp, ledger-core/src/core/wallet/WalletStore.cpp, ledger-core/test/integration/BaseFixture.cpp, ledger-core/test/integration/BaseFixture.hpp
This is the final piece to completely segregate the old WalletPool.
=> Add WalletStore.

core/lib/secp256k1/CMakeLists.txt, tools/build_linux_arm/build.sh
This could be useful for some users (internal to Ledger too).
=> Add script to build libcore for Linux for ARM architecture

ledger-core-ethereum/test/CMakeLists.txt, ledger-core-ethereum/test/Fixtures.cpp, ledger-core-ethereum/test/Fixtures.hpp, ledger-core-ethereum/test/cmake, ledger-core-ethereum/test/lib, ledger-core-ethereum/test/main.cpp
=> Modularize Ethereum test fixtures.

ledger-core-ethereum/inc/ethereum/EthereumLikeCoinID.hpp, ledger-core-ethereum/inc/ethereum/EthereumLikeCurrencies.hpp, ledger-core-ethereum/inc/ethereum/database/Migrations.hpp, ledger-core-ethereum/src/ethereum/EthereumLikeCurrencies.cpp, ledger-core-ethereum/src/ethereum/EthereumLikeWallet.cpp, ledger-core-ethereum/src/ethereum/factories/EthereumLikeWalletFactory.cpp, ledger-core-ethereum/test/CMakeLists.txt, ledger-core-ethereum/test/TransactionTests.cpp, ledger-core-ripple/test/TransactionTest.cpp, ledger-core/test/integration/TransactionTestHelper.hpp
=> Migrate Ethereum transaction tests to the modularized interface.

core/src/wallet/ripple/explorers/api/RippleLikeTransactionParser.cpp
=> Fix Ripple transaction dates

core/src/wallet/tezos/TezosLikeAccount.cpp, core/test/integration/synchronization/tezos_synchronization.cpp
This is related to : https://ledgerhq.atlassian.net/browse/LLC-507
=> Fix XTZ: creation of same account (with KT accounts) under two different wallets

core/src/wallet/bitcoin/database/BitcoinLikeUTXODatabaseHelper.cpp, core/test/integration/synchronization/synchronization_tests.cpp
This is related to : https://ledgerhq.atlassian.net/browse/LLC-486
=> Paginate properly UTXOs

core/idl/wallet/ripple/ripple_like_wallet.djinni, core/src/api/RippleLikeTransaction.hpp, core/src/database/DatabaseSessionPool.hpp, core/src/database/migrations.cpp, core/src/database/migrations.hpp, core/src/jni/jni/RippleLikeTransaction.cpp, core/src/wallet/common/explorers/AbstractBlockchainExplorer.h, core/src/wallet/ripple/RippleLikeAccount.cpp, core/src/wallet/ripple/RippleLikeAccount.h, core/src/wallet/ripple/api_impl/RippleLikeTransactionApi.cpp, core/src/wallet/ripple/api_impl/RippleLikeTransactionApi.h, core/src/wallet/ripple/database/RippleLikeTransactionDatabaseHelper.cpp, core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.cpp, core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.h, core/src/wallet/ripple/explorers/RippleLikeBlockchainExplorer.h, core/src/wallet/ripple/explorers/api/RippleLikeTransactionParser.cpp, core/src/wallet/ripple/explorers/api/RippleLikeTransactionsBulkParser.h, core/test/integration/synchronization/ripple_synchronization.cpp
=> Fix Ripple negative balances (TX pagination + TX status check)

ledger-core-ethereum/test/KeychainTests.cpp, ledger-core-ethereum/test/SynchronizationTests.cpp, ledger-core-ripple/test/RippleKeychainTest.cpp, ledger-core-ripple/test/SynchronizationTest.cpp
Thanks @alekece for pointing that out!
=> Add wait() for addCurrency in tests in ETH and XRP.

ledger-core-bitcoin/inc/bitcoin/explorers/BitcoinLikeBlockchainExplorer.hpp, ledger-core-bitcoin/inc/bitcoin/observers/BitcoinLikeBlockchainObserver.hpp, ledger-core-bitcoin/src/bitcoin/BitcoinLikeAddress.cpp, ledger-core-bitcoin/src/bitcoin/BitcoinLikeExtendedPublicKey.cpp
Optional and Logger had small typos
DjinniHelpers file does not exist anymore
=> Fix includes for btc files

ledger-core-ethereum/test/Fixtures.cpp, ledger-core-ethereum/test/Fixtures.hpp, ledger-core-ethereum/test/SynchronizationTests.cpp, ledger-core/test/integration/BaseFixture.cpp, ledger-core/test/integration/BaseFixture.hpp
The purpose of this PR is to improve our current `BaseFixture` class to ease the readability of our current tests and create a common scope for new coin tests.
I also removed unwanted log message and start to remove coin-specific global variable such as `P2PKH_MEDIUM_XPUB_INFO`.
=> Improve integration BaseFixture

.circleci/build_lib.sh, .circleci/config.yml, .circleci/copy_artifacts.sh
=> Fix segfault in Linux + node with OpenSSL 1.1. (node > 8).

ledger-core-ethereum/test/KeychainTests.cpp, ledger-core-ripple/test/RippleKeychainTest.cpp, ledger-core/test/integration/KeychainFixture.hpp
This PR introduces the new `KeychainFixture` class and eases the way to write test to check keychain derivation and so on.
=> Add keychain fixture

ledger-core/idl/wallet_store.djinni, ledger-core/inc/core/Services.hpp, ledger-core/inc/core/wallet/WalletStore.hpp, ledger-core/src/core/Services.cpp, ledger-core/src/core/wallet/WalletStore.cpp
=> Fix ledger-core for callback2.

ledger-core-ethereum/src/ethereum/EthereumLikeCurrencies.cpp, ledger-core-ethereum/test/AccountTests.cpp, ledger-core-ethereum/test/CMakeLists.txt
This PR contains the UNIQUE account test for ETH.
BTW, the test fails on the latest expectation and I can't figure out if this is a regression or only a bad test ?
@KhalilBellakrid can you check it (see the `TODO` comment) ?
=> Migrate ETH account test

core/test/integration/synchronization/synchronization_tests.cpp, ledger-core-bitcoin/inc/bitcoin/BitcoinLikeAccount.hpp, ledger-core-bitcoin/inc/bitcoin/database/BitcoinLikeTransactionDatabaseHelper.hpp, ledger-core-bitcoin/inc/bitcoin/explorers/BitcoinLikeBlockchainExplorer.hpp, ledger-core-bitcoin/inc/bitcoin/transactions/BitcoinLikeAbstractTransactionParser.hpp, ledger-core-bitcoin/src/bitcoin/BitcoinLikeAccount.cpp, ledger-core-bitcoin/src/bitcoin/database/BitcoinLikeTransactionDatabaseHelper.cpp, ledger-core-bitcoin/src/bitcoin/database/BitcoinLikeUTXODatabaseHelper.cpp, ledger-core-bitcoin/src/bitcoin/io/BitcoinLikeInputParser.cpp, ledger-core-bitcoin/src/bitcoin/io/BitcoinLikeOutputParser.cpp, ledger-core-bitcoin/src/bitcoin/transactions/BitcoinLikeTransactionParser.cpp, ledger-core/inc/core/synchronizers/AbstractBlockchainExplorerAccountSynchronizer.hpp
This goal of this PR is to backport all the BTC fixes from develop to our modularization branch.
=> Segregate BTC fixes

ledger-core-ripple/idl/idl.djinni, ledger-core-ripple/inc/ripple/RippleLikeAccount.hpp, ledger-core-ripple/inc/ripple/RippleLikeTransaction.hpp, ledger-core-ripple/inc/ripple/database/Migrations.hpp, ledger-core-ripple/inc/ripple/explorers/NodeRippleLikeBlockchainExplorer.hpp, ledger-core-ripple/inc/ripple/explorers/RippleLikeBlockchainExplorer.hpp, ledger-core-ripple/inc/ripple/explorers/RippleLikeTransactionsBulkParser.hpp, ledger-core-ripple/src/ripple/RippleLikeAccount.cpp, ledger-core-ripple/src/ripple/RippleLikeTransaction.cpp, ledger-core-ripple/src/ripple/RippleLikeTransactionDatabaseHelper.cpp, ledger-core-ripple/src/ripple/database/Migrations.cpp, ledger-core-ripple/src/ripple/explorers/NodeRippleLikeBlockchainExplorer.cpp, ledger-core-ripple/src/ripple/explorers/RippleLikeTransactionParser.cpp, ledger-core-ripple/test/SynchronizationTest.cpp, ledger-core/inc/core/explorers/AbstractBlockchainExplorer.hpp
=> Cross-port recent XRP fixes on pagination and dates

ledger-core-ripple/test/AccountTests.cpp, ledger-core-ripple/test/CMakeLists.txt
All you have to know is in the PR title :trollface:
=> Add XRP account test

core/src/bitcoin/bech32/Bech32Factory.cpp, core/src/bitcoin/bech32/Bech32Parameters.cpp, core/test/bitcoin/address_test.cpp, core/test/integration/BaseFixture.cpp, core/test/integration/BaseFixture.h, core/test/integration/synchronization/synchronization_tests.cpp
This is related to : https://ledgerhq.atlassian.net/browse/LLC-492
**NOTE:** HODL flag will be removed after fixing issue on DGB app.
=> DGB: support of bech32 addresses

ledger-core/CMakeLists.txt
This PR aims to resolve a new bug occuring since the backport of PostgreSQL - quick and easy.
=> Fix build without PG_SUPPORT

ledger-core/src/CMakeLists.txt
=> Do not include PG header if we’re not compiling with PG_SUPPORT.

core/src/wallet/bitcoin/BitcoinLikeAccount.cpp, core/src/wallet/common/AbstractAccount.cpp, core/src/wallet/common/AbstractAccount.hpp, core/src/wallet/ethereum/EthereumLikeAccount.cpp, core/src/wallet/ripple/RippleLikeAccount.cpp, core/src/wallet/tezos/TezosLikeAccount2.cpp, core/test/integration/keychains/p2pkh_keychain_test.cpp, core/test/integration/synchronization/synchronization_tests.cpp
This is related to : https://ledgerhq.atlassian.net/browse/LLC-531
=> Resync after wipe

ledger-core/idl/database.djinni, ledger-core/inc/core/database/proxy_backend/SociProxy.hpp, ledger-core/lib/soci/core/session.cpp, ledger-core/lib/soci/core/session.h, ledger-core/lib/soci/core/soci-backend.h, ledger-core/lib/soci_postgresql/session.cpp, ledger-core/lib/soci_postgresql/soci-postgresql.h, ledger-core/lib/soci_sqlite3/session.cpp, ledger-core/lib/soci_sqlite3/soci-sqlite3.h, ledger-core/src/core/database/proxy_backend/session.cpp, ledger-core/test/database/MemoryDatabaseProxy.cpp
Cross-port my recent fix for `soci` timeout deconnections.
=> Cross-port #498 into design/modularization.

core/src/net/HttpClient.cpp, core/src/net/HttpClient.hpp, core/src/wallet/common/explorers/AbstractLedgerApiBlockchainExplorer.h, core/src/wallet/ripple/explorers/ApiRippleLikeBlockchainExplorer.cpp, core/src/wallet/ripple/explorers/NodeRippleLikeBlockchainExplorer.cpp
This is related to : https://ledgerhq.atlassian.net/browse/LLC-586
=> Better granularity of HTTP errors

ledger-core/CMakeLists.txt, ledger-core/test/integration/CMakeLists.txt, ledger-core/test/lib/libledger-test/CMakeLists.txt
=> Fix ssl not being properly imported whith BUILD_TESTS=ON and no SYS_OPENSSL=OFF.

core/src/net/HttpClient.hpp
- Apply changed made on HttpClient.cpp to HttpClient.hpp
=> Fix Http client with JSON SAX parser in case of error

ledger-core-bitcoin/src/bitcoin/BitcoinLikeAccount.cpp, ledger-core-bitcoin/test/SynchronizationTests.cpp, ledger-core-ethereum/src/ethereum/EthereumLikeAccount.cpp, ledger-core-ripple/src/ripple/RippleLikeAccount.cpp, ledger-core/inc/core/wallet/AbstractAccount.hpp, ledger-core/src/core/wallet/AbstractAccount.cpp
This PR aims to backport all the changes from the [PR #494](https://github.com/LedgerHQ/lib-ledger-core/pull/494)
=> Backport PR #494

ledger-core-ethereum/src/ethereum/explorers/EthereumLikeTransactionParser.cpp, ledger-core/inc/core/database/Migrations.hpp, ledger-core/inc/core/synchronizers/AbstractBlockchainExplorerAccountSynchronizer.hpp
This PR aims to backport all the changes from the [PR #483 ](https://github.com/LedgerHQ/lib-ledger-core/pull/483)
=> Backport PR #483

ledger-core-ethereum/idl/idl.djinni, ledger-core-ethereum/inc/ethereum/EthereumLikeAccount.hpp, ledger-core-ethereum/inc/ethereum/explorers/EthereumLikeBlockchainExplorer.hpp, ledger-core-ethereum/inc/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.hpp, ledger-core-ethereum/src/ethereum/EthereumLikeAccount.cpp, ledger-core-ethereum/src/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.cpp, ledger-core-ethereum/test/ExplorerTests.cpp
This PR aims to backport all the changes from the [PR #429 ](https://github.com/LedgerHQ/lib-ledger-core/pull/429)
=> Backport PR #429

ledger-core-ripple/idl/ledger-core, ledger-core-tezos/idl/ledger-core, ledger-core-tezos/src/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp, ledger-core-tezos/test/SynchronizationTests.cpp, ledger-core/inc/core/utils/ConfigurationMatchable.hpp, ledger-core/src/core/utils/ConfigurationMatchable.cpp
This PR aims to backport all the changes from the [PR #513](https://github.com/LedgerHQ/lib-ledger-core/pull/513)
=> Backport #513

core/src/math/Base58.cpp
This is related to : https://ledgerhq.atlassian.net/browse/LVS-123
=> Fix Base58 for XRP

doc/rfcs/0000-template.md, doc/rfcs/0001-modularization.md, doc/rfcs/0002-modularized-node-packaging.md
This PR provides the RFC / design document about the packaging design for the new modularized Core regarding node / NPM.
[Rendered](https://github.com/phaazon/lib-ledger-core/blob/modularization/design-doc-pkg/doc/rfcs/0002-modularized-node-packaging.md).
=> Add the 0002-modularized-node-packaging design document.

core/src/wallet/stellar/StellarLikeAccount.cpp, core/src/wallet/stellar/database/StellarLikeAccountDatabaseHelper.cpp
- Fetch sequence from the explorer instead of relying on database. This ensures that the sequence is up to date with the network.
- Fix a minor issue on SQL create account query.
=> Minor fixes on XLM implementation

.circleci/setup_debian.sh, .circleci/setup_macos.sh
That commit should fix the situation with failing sbt downloads.
=> Update SBT to version 1.3.10 on the Debian CI.

core/src/wallet/cosmos/explorers/GaiaCosmosLikeBlockchainExplorer.cpp
This should help make getEstimatedGasLimit more reliable
=> [cosmos] Add baseline gas cost to estimation

core/src/wallet/cosmos/CosmosLikeWallet.cpp
This support is necessary for Live to handle synchronizations from
"cleaned cache"
=> [cosmos] Add support for ExtendedKeyAccountCreationInfo

core/src/wallet/cosmos/explorers/GaiaCosmosLikeBlockchainExplorer.cpp
The estimation was inaccurate anyway because Gaia doesn't include the
cost of reading from and writing to the state during the simulation, so
the gas estimate is always going to be strongly underevaluated.
And the change here seems also break ledger-live-common; so
better to revert every possible cause of bugs that doesn't bring value.
The bug occurs because Ledger Live asks for gas estimations on very incomplete "Transaction", so the call for `transaction->serializeForSignature()` does not match the necessary preconditions and fails.
=> Revert gas estimation base value

core/src/database/migrations.hpp, core/test/integration/synchronization/synchronization_btc_rbf_tests.cpp, core/test/lib/libledger-test/UvThreadDispatcher.cpp, core/test/lib/libledger-test/UvThreadDispatcher.hpp
<winsock2.h> should be inlcuded before <windows.h>
=> Fix ledger-test compilation for windows

.circleci/build_lib.sh, .circleci/config.yml, .circleci/setup_debian.sh, .circleci/setup_macos.sh, Dockerfile, core/idl/wallet/wallet_pool.djinni, core/src/api/WalletPool.hpp, core/src/jni/jni/WalletPool.cpp, core/src/wallet/pool/WalletPool.cpp, core/src/wallet/pool/WalletPool.hpp, core/src/wallet/pool/api/WalletPoolApi.cpp
New PreferencesBackend update broke the API for WalletPool::newInstance. I reverted the API to keep the same API.
For custom preferences API, users will have to use WalletPoolBuilder
=> Make preferences API retro-compatible

.circleci/config.yml
Change the docker container in
publish_jar job
=> Publish with debian not darwin

core/src/api/StellarLikeNetworkParameters.hpp, core/src/database/DatabaseSessionPool.hpp, core/src/database/migrations.cpp, core/src/database/migrations.hpp, core/src/wallet/pool/database/CurrenciesDatabaseHelper.cpp
This PR adds migration 22, to add a field for Muxed address version in stellar_currencies table.
=> [XLM] Create a migration for MuxedVersion

.circleci/config.yml, core/src/wallet/bitcoin/transaction_builders/BitcoinLikeStrategyUtxoPicker.cpp, core/src/wallet/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.cpp, core/test/integration/ledger_api_blockchain_explorer_tests.cpp
I am pretty sure that PR doesn't deserve a proper description.
=> Fix CI for debian & gcc-6

ledger-core-bitcoin/idl/addresses.djinni, ledger-core-bitcoin/idl/idl.djinni, ledger-core-bitcoin/inc/bitcoin/BitcoinLikeAccount.hpp, ledger-core-bitcoin/inc/bitcoin/keychains/BitcoinLikeKeychain.hpp, ledger-core-bitcoin/inc/bitcoin/keychains/CommonBitcoinLikeKeychains.hpp, ledger-core-bitcoin/src/bitcoin/BitcoinLikeAccount.cpp, ledger-core-bitcoin/src/bitcoin/keychains/CommonBitcoinLikeKeychains.cpp
=> Create Keychain API

core/src/wallet/tezos/TezosLikeAccount2.cpp
Save tx counter and use it when explorer_counter < saved_counter, should solve the bug in which only the first tx will be accepted by the networks because the explorer didn't have the time to increment it
=> [Tezos] Fix bug when sending multiple transactions in a row

core/src/wallet/tezos/TezosLikeAccount2.cpp
This reverts commit a99d894a3f4839321c31c2a9eb1ecfee62c35fd7.
=> Revert "Fix bug when sending multiple transactions in a row"

core/idl/preferences/preferences.djinni, core/src/api/PreferencesBackend.hpp, core/src/jni/jni/PreferencesBackend.cpp, core/src/jni/jni/PreferencesBackend.hpp, core/src/preferences/PreferencesBackend.cpp, core/src/preferences/PreferencesBackend.hpp
Fix bug: https://ledgerhq.atlassian.net/browse/LLC-697
This bug is caused by djinni definition of Preferencesbackend.
Preferencesbackend java object can not be converted to C++ object correctly
=> [LLC-697]Fix preferenceBack API

core/idl/wallet/tezos/tezos_like_wallet.djinni, core/src/api/TezosConfiguration.cpp, core/src/api/TezosConfiguration.hpp, core/src/api/TezosConfigurationDefaults.cpp, core/src/api/TezosConfigurationDefaults.hpp, core/src/api/TezosLikeAccount.hpp, core/src/jni/jni/TezosLikeAccount.cpp, core/src/wallet/tezos/TezosLikeAccount.cpp, core/src/wallet/tezos/TezosLikeAccount.h, core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.cpp, core/src/wallet/tezos/explorers/ExternalTezosLikeBlockchainExplorer.h, core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.cpp, core/src/wallet/tezos/explorers/NodeTezosLikeBlockchainExplorer.h, core/src/wallet/tezos/explorers/TezosLikeBlockchainExplorer.h
Add a method to get FA1.2 token balance for a given tz address using better-call-dev api.
=> Add a getTokenBalance method to tezos account and explorers

core/test/integration/synchronization/ethereum_synchronization.cpp, core/test/integration/synchronization/synchronization_tests.cpp, core/test/lib/cpp-httplib/httplib.h
=> fix build error

core/src/wallet/bitcoin/synchronizers/BlockchainExplorerAccountSynchronizer.cpp, core/src/wallet/bitcoin/synchronizers/BlockchainExplorerAccountSynchronizer.h, core/src/wallet/common/synchronizers/AbstractBlockchainExplorerAccountSynchronizer.h
Create an independent synchronizer for bitcoin. So that the bitcoin synchronizer logic doesn't impect other currencies.
=> Create an independent synchronizer for bitcoin

core/test/async/threading_tests.cpp, core/test/lib/libledger-test/UvThreadDispatcher.cpp, core/test/lib/libledger-test/UvThreadDispatcher.hpp
Fix the implementation of thread pool execution context for testlib
=> Fix the implementation of thread pool for testlib

core/src/config/Networks.cpp, core/src/wallet/currencies.cpp
=> Rename stargate testnet chain

core/src/wallet/cosmos/explorers/StargateGaiaCosmosLikeBlockchainExplorer.cpp
If the account doesn't exist, we return a mostly empty account.
=> Catch 5xx for getAccount endpoint in Cosmos

.circleci/config.yml, CHANGELOG.md, CMakeLists.txt, appveyor.yml, core/src/wallet/stellar/StellarLikeAccount.cpp, core/src/wallet/stellar/xdr/models.hpp
Prevents from writting them in DB and outputs a warning
=> Hotfix handling of unknown stellar transactions operation types

.github/workflows/tests.yml, core/src/wallet/bitcoin/BitcoinLikeAccount.cpp, core/src/wallet/bitcoin/synchronizers/BlockchainExplorerAccountSynchronizer.cpp
=> [VG-944] 4.1 – Port optimistic update fix

core/src/wallet/bitcoin/keychains/CommonBitcoinLikeKeychains.cpp, core/src/wallet/bitcoin/keychains/CommonBitcoinLikeKeychains.hpp, core/test/integration/CMakeLists.txt, core/test/integration/keychains/common_bitcoin_keychain_test.cpp, core/test/integration/keychains/keychain_test_helper.h, core/test/integration/keychains/p2sh_keychain_test.cpp
=> VG-1728: Remove the use of internal state in keychains

CMakeLists.txt, core/src/wallet/tezos/TezosLikeAccount2.cpp, core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.cpp, core/src/wallet/tezos/api_impl/TezosLikeTransactionApi.h
* Tezos fees calculation according to a [recommended formula](https://tezosguides.com/wallet_integration/basics/fee_schedule/)
* bump patch version to `4.1.2`
=> [VG-2554] Fix tezos fees calculation

core/test/lib/libledger-test/MemPreferencesBackend.cpp, core/test/lib/libledger-test/MemPreferencesBackend.hpp, core/test/lib/libledger-test/MongooseSimpleRestServer.cpp, core/test/lib/libledger-test/MongooseSimpleRestServer.hpp, core/test/net/http_client_tests.cpp
This PR fixes several blinking tests.
=> Fix CI tests

CMakeLists.txt, core/src/wallet/stellar/StellarLikeWallet.cpp, core/test/integration/account_creation_tests.cpp
* Bump patch version to `4.1.13`
* Fix idempotent stellar account creation
* Add integration tests on idempotent account creation for
* Stellar
* Ripple
* Ethereum
* [VG-5126](https://ledgerhq.atlassian.net/browse/VG-5126)
=> VG-5126 fix(Stellar): idempotent account creation

.circleci/config.yml
Failing because statics.ledger.com has been decommissioned
Removed because not used & maintained
=> Remove failing generate_doc job

core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
=> Limit UTXOs for transactions

core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
This reverts commit 90371049c02604b7e26bf558f455bbabaff85231.
=> Revert "Limit UTXOs for transactions (#906)"

core/idl/wallet/configuration.djinni, core/src/api/Configuration.cpp, core/src/api/Configuration.hpp, core/src/api/WalletPool.hpp, core/src/wallet/bitcoin/BitcoinLikeWallet.cpp, core/src/wallet/common/AbstractWallet.cpp, core/src/wallet/pool/WalletPool.cpp
- separate the conf of balance cache (TTL_BALANCE_CACHE) from block cache (TTL_BLOCK_CACHE)
=> VG-11192 - Separately configurable balance cache TTL

core/src/wallet/bitcoin/BitcoinLikeWallet.cpp, core/src/wallet/bitcoin/BitcoinLikeWallet.hpp, core/src/wallet/bitcoin/explorers/LedgerApiBitcoinLikeBlockchainExplorer.cpp, core/src/wallet/bitcoin/explorers/LedgerApiBitcoinLikeBlockchainExplorer.hpp
To reduce number of calls made to explorer
=> fix(explorer): Move block cache at higher level

core/src/wallet/bitcoin/database/BitcoinLikeOperationDatabaseHelper.cpp
same as https://github.com/LedgerHQ/lama-bitcoin/pull/548/files
=> Fix(sync): Update block_height on tx sync
